<style>

.refresh-container {
 /*position:absolute;*/
 top:0;
 right:0;
 background:rgba(200,200,200,0.25);
 width:100%;
 height:100%;
 display: none;
 text-align:center;
 z-index:4;
}

.refresh-spinner {
 padding: 30px;
 opacity: 0.8;
}

.checkbox label:after {
    content: '';
    display: table;
    clear: both;
}

.checkbox .cr{
    position: relative;
    display: inline-block;
    border: 1px solid #a9a9a9;
    border-radius: .25em;
    width: 1.8em;
    height: 1.8em;
    float: left;
    margin-right: .5em;
}

.checkbox .cr .cr-icon {
    position: absolute;
    font-size: 1.2em;
    line-height: 0;
    top: 50%;
    left: 12%;
}

.checkbox label input[type="checkbox"]{
    display: none;
}

.checkbox label input[type="checkbox"] + .cr > .cr-icon {
    transform: scale(3) rotateZ(-20deg);
    opacity: 0;
    transition: all .3s ease-in;
}

.checkbox label input[type="checkbox"]:checked + .cr > .cr-icon {
    transform: scale(1) rotateZ(0deg);
    opacity: 1;
}
</style>  


<div class="container-fluid">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading" role="tab" id="headingTwo" data-toggle="collapse" data-parent="#accordion" href="#consulta_fechas" aria-expanded="true" aria-controls="collapseTwo">SELECCION DE PENDIENTES POR FECHA</div>
            <div class="panel-body" id="consulta_fechas">
                <form action="<?=BASE_URL?>pendietes/getDataTableClientesPendientes" name="formulario_consulta_pendientes" method="POST">
                    <div class="panel-body">
                        <div class="col-md-6 fields-container">
                            <label for="fecha_inicio">FECHA INICIO REPORTE:</label>
                            <input type="date" class="form-control" name="fecha_inicio" id="fecha_inicio" data-required="true">
                            <small class="help-error-block" style="color: #e32"></small>
                        </div>
                        <div class="col-md-6 fields-container">
                            <label for="fecha_fin">FECHA FIN REPORTE:</label>
                            <input type="date" class="form-control" name="fecha_fin" id="fecha_fin" data-required="true">
                            <small class="help-error-block" style="color: #e32"></small>
                        </div>
                    </div>
                    <div style="margin-top:6px">
                        <button class="btn btn-success" id="btn-consultar">Consultar <span class="glyphicon glyphicon-search"></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- CONTENEDOR RECARGA NUEVO CLIENTE ESTADO CAPTURA -->
<div class="container-fluid hidden" id="container-pendings">
    <div class="panel panel-default">       
        <div class="panel-body panel-refresh">            
            <div class="content-list-pendientes">
                <!-- TABLA DE REPORTE DE LISTADO DE CAPTURAS HECHAS POR EL USUARIO -->
                <table name="table-pendientes" id="table-pendientes" class="table table-striped table-bordered" cellspacing="0" width="100%" style="max-height: 480px; overflow-y: auto"></table>
                <div class="form-group hidden" id="sendMailContainer">
                    <div class="form-group">Seleccionados <span id="cantSeleccionados"></span> de <span id="totalPendientes"></span>.</div>
                    <button class='btn btn-success' id="sendMailPendings" disabled>
                        <span id="button_text">Enviar correo.</span>
                        <span class='glyphicon glyphicon-envelope'></span>
                    </button>
                </div>
            </div>            
        </div>
    </div>
</div>