<style>  
.panel-refresh {
  padding: 0px 0px 10px 0px;
}
 
.refresh-container {
 /*position:absolute;*/
 top:0;
 right:0;
 background:rgba(200,200,200,0.25);
 width:100%;
 height:100%;
 display: none;
 text-align:center;
 z-index:4;
}

.refresh-spinner {
 padding: 30px;
 opacity: 0.8;
}
</style>  

<!-- CONTENEDOR RECARGA NUEVO CLIENTE ESTADO CAPTURA -->
<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <a id="ReloadClient" href="javascript:void(0)" class="btn btn-default pull-left" style="margin-left: 10px;"><i class="glyphicon glyphicon-repeat"></i></a>
                <div class="pull-left col-xs-4 col-md-2">
                    <div class="input-group">
                        <input type="text" name="SearchClienteDocument" class="form-control" placeholder="Ingrese el documento del cliente para visualizar">
                        <span class="input-group-addon" id="btn-SearchClienteDocument" style="cursor:pointer;"><span class="glyphicon glyphicon-search"></span></span>
                    </div>
                </div>
                <a href="javascript:void(0)" id="list-alt" type="button" class="btn btn-default pull-right"  style="margin-right: 10px;"><i class="glyphicon glyphicon-list-alt"></i></a>
                <a href="javascript:void(0)" id="RefreshForm" class="btn btn-default pull-right" style="margin-right: 10px; display: none;"><i class="glyphicon glyphicon-refresh"></i></a>
                <a href="javascript:void(0)" id="ViewDocumentsClient" class="btn btn-default pull-right" style="margin-right: 10px; display: none;"><i class="glyphicon glyphicon-folder-open"></i></a>
                <a href="javascript:void(0)" id="ViewCliente" class="btn btn-default pull-right" style="margin-right: 10px; display: none;"><i class="glyphicon glyphicon-user"></i></a>
            </div>
        </div>
        <div class="panel-body">

            <!-- CLIENTE ACTIVO -->
            <input type="hidden" name="view_cliente">

            <!-- TABLA DE REPORTE DE LISTADO DE CAPTURAS HECHAS POR EL USUARIO -->
            <div id="table-pendientes" class="panels-content table-responsive" style="display: none; padding: 15px;">
              <table id="table-content" class="table table-striped table-bordered " cellspacing="0" width="100%"></table>
            </div>
              
            <!-- CONTENEDOR DEL FORMULARIO VISUALIZADO POR EL USUARIO -->
            <div id="content-sarlaft" class="panels-content">
              
                <div class="sarlaf-messages">
                    <div class="alert alert-success" style="margin-top: 20px;">
                        Para cargar un cliente <strong>DAR CLIC EN LA LUPA </strong> <span class="glyphicon glyphicon-repeat"></span>.
                    </div>
                </div>
                <div id="conten-form">
                  <!-- ACA SE VA A CARGAR EL FORMULARIO DEL CLIENTE NATURAL O JURIDICO -->
                </div>
            </div>
  
            <div id="documentos-clientePDF" class="panels-content" style="display: none; padding: 15px;">
              <div class="alert alert-info"> DOCUMENTOS DEL CLIENTE </div>
                <table id="table-listado-documentos-cliente" class="table table-striped table-bordered " cellspacing="0" width="100%"></table>
                <!-- ACA SE CARGARAN LOS DOCUMENTOS DEL CLIENTE -->
            </div>
        </div>
    </div>
</div>