<script src="<?=BASE_URL?>views/home/js/natural.js"></script>
<link rel="stylesheet" href="<?= BASE_URL;?>public/css/reset.css">
<style type="text/css">
	input[type="email"]{
		text-transform: lowercase;
	}

	input[type="text"]{
		text-transform: uppercase;
	}

	input[id="txtLugar_expedicion_documento"]{
		display: none;
		margin: 10px 0 10px 0;
	}
	input[id="txtLugarNacimiento"], input[id="txtOcupacion"] {
		margin: 10px 0 10px 0;
		display: none;
	}

 	.direccion {
		display: flex;
		align-items: center;
	}

	.containerDireccion {
		box-sizing: border-box;
		margin: 10px 0;
	}

	.containerDireccion .controlDireccion {
		box-sizing: border-box;
		display: inline-block;
		padding: 10px;
	}

	.divHabilitaDireccion {
		margin: 10px 0;
	}

	.checkDireccion {
		margin-left: 5px;
	} 

	.muestraDireccion {
		display: none;
	}
</style>

<!-- accordion con los datos del formulario de natural version 2.0 --> 
<div id="panels-form-captura-natural">
	<div class="form-person-header">
	    <h2><?=$titulo?></h2>
	    <span class="required-fields-label">* Campos obligatorios</span>
		
	</div>
	<ol class="breadcrumb" id="tags-proceso-form-natural">
		<?php $captura_enabled = array(1,4,3,11,13);?>
		<?php $completitud_enabled = array(6,9,10);?>
		<?php $verificacion_enabled = array(5,6,10,3);?>
		<?=(in_array($InfoCliente["estado_formulario_id"],$captura_enabled)) ? "<li><a href='javascript:void(0)'>Captura</a></li>" : "<li class='active' style='pointer-events: none;opacity: 0.4;'>Captura</li>"?>
	  	<?=((in_array($InfoCliente["estado_formulario_id"],$completitud_enabled) || $InfoCliente["estado_formulario_id"] == 3)) ? "<li><a href='javascript:void(0)'>Completitud</a></li>" : "<li class='active no-completitud' style='pointer-events: none;opacity: 0.4;'>Completitud</li>"?>
	  	<?=((in_array($InfoCliente["estado_formulario_id"],$verificacion_enabled))) ? "<li><a href='javascript:void(0)'>Verificación</a></li>" : "<li class='active' style='pointer-events: none;opacity: 0.4;'>Verificación</li>"?>
	</ol>

	<!-- ALERTA DEL ESTADO DEL CLIENTE -->
	<div class="alert alert-info col-md-12" role="alert">
	  	ESTADO: <strong style="font-weight: bold; text-transform: uppercase;" id="estado_form_sarlaft"><?=(isset($cliente["falta"]) && $InfoCliente["estado_formulario_id"] != 1) ? $InfoCliente["ESTADO_FORM"]." - ".$cliente["falta"] : $InfoCliente["ESTADO_FORM"];?></strong>
	</div>
	<!-- JAV01 -->
    <?php if (isset($nombreCliente)):?>
        <div class="form-group" style="overflow: hidden; padding: 8px 0 12px 4px">
            <label style="font-weight: bold; font-family: Verdana; font-size: 14px; float: left;">Nombre del cliente: <?=strtoupper($nombreCliente)?> </label>    
            <hr>
        </div>
    <?php endif;?>
	<!-- FORMULARIO DE CAPTURA -->
	<form action="<?=BASE_URL?>home/saveCaptura" method="POST" autocomplete="off" name='form-captura-persona-natural' id="form-captura-persona-natural">

		<input type="hidden" name="tipo_cliente" id="tipo_cliente" value="<?=$InfoCliente['TIPO_PERSONA']?>">
		<input type="hidden" name="cliente" id="cliente" value="<?=$InfoCliente['cliente_id']?>">
		<input type="hidden" id ="captura_sarlaft_id" name="captura_sarlaft_id" value="<?=$InfoCliente['formulario_id']?>">
		<input type="hidden" id ="estado_form_id" name="estado_form_id" value="<?=$InfoCliente["estado_formulario_id"]?>">	
		<div class="panel-group categorias" id="accordion" role="tablist" aria-multiselectable="true">

			<?php if(!in_array($InfoCliente["estado_formulario_id"],[1])): ?>
                <div class="pull-right col-md-4">
                    <div class="pull-right form-group <?= (!isset($InfoCliente["NUMERO_MARCADO"]) ? 'hidden' : '' ) ?>" id="numero_llamada_inbound" style="margin-left: 10px;">
                        <label for="numero_llamada_inbound">Numero de telefono:</label>
                        <input type="text" name="numero_llamada_inbound" class="form-control" onkeydown="OnlyNumbers(this)" <?= (isset($InfoCliente["NUMERO_MARCADO"]) ? 'value="' . $InfoCliente["NUMERO_MARCADO"] .  '"' : '' ) ?>>
                    </div>
                    <div class="pull-right form-group">
                        <label for="llamada_cliente_sarlaft">Tipo de Llamada:</label>
                        <select name="llamada_cliente_sarlaft" class="form-control">
                            <option value="">Elija una opción...</option>
                            <?php if(!in_array($InfoCliente["estado_formulario_id"],[14])): ?>
                            <option value="INBOUND">LLAMADA ENTRANTE</option>
                            <?php endif; ?>
                            <option value="OUTBOUND">LLAMADA SALIENTE</option>
                            <option value="MODIFICACION">MODIFICACIÓN</option>
                        </select>
                    </div>
                </div>
            <?php endif; ?>

			<?php if(!in_array($InfoCliente["estado_formulario_id"],[1,2])): ?>
				<!-- SECCION DE TIPOLOGIAS -->
				<div class="panel section-form" captura="false">
				  <div class="panel-heading" role="tab" id="heading" data-toggle="collapse" data-parent="#accordion_completitud" href="#tipologias_completitud" aria-expanded="true" aria-controls="collapseTwo">
				    <h4 class="panel-title">
				    <a class="collapsed" role="button">
				      <strong>TIPOLOGIAS</strong>
				    </a>
				  </h4>
				  </div>
				  <div id="tipologias_completitud" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading">
				    <div class="panel-body">
				    	<div class="content-radio-buttons col-md-12">
				    		<label class="control-label title">Se realiza de manera:</label>
							<div class="form-group">
								<?php $tipologia = isset($cliente["tipologia"]) ? explode(',',$cliente["tipologia"]) : array() ?>
								<!-- <label class="radio-inline"><input type="checkbox" name="tipologia[DOCUMENTAL]" value="DOCUMENTAL" <?=(in_array("DOCUMENTAL", $tipologia)) ? "checked" : ""; ?> class="radios persona_publica">Documental</label> -->
		                        <label class="radio-inline"><input type="checkbox" name="tipologia[TELEFONICA]" value="TELEFONICA" <?=(in_array('TELEFONICA',$tipologia)) ? "checked" : ""; ?> class="radios persona_publica" onclick="checkboxEnabledField(true,this,'div#estado_tipologia','hide')">Telefonica</label>
			    			</div>
				    	</div>
				    	<div id="estado_tipologia" <?=(!in_array('TELEFONICA',$tipologia)) ? 'style="display: none"' : ''?>>
				    		<div class="container-fluid">
				    			<div class="row">
				    				<div class="form-group col-md-8">
						    			<label class="control-label">Estado de Tipologia:</label>
						    			<select name="estado_tipologia" class="form-control" <?=(in_array($InfoCliente["estado_formulario_id"],[9,14])) ? 'disabled' : '' ?>>
						    				<option value='' hidden>Selecione una tipologia</option>
						    				<?php foreach($tipologias as $valueTipologia):?>
						    					<option value="<?=$valueTipologia['id']?>" <?=(isset($cliente["estado_tipologia"]) && $cliente["estado_tipologia"] == $valueTipologia["id"] ? 'selected' : '')?>><?=$valueTipologia["tipologia"]?></option>
						    				<?php endforeach; ?>
						    			</select>
						    		</div>
						    		<div class="col-md-4" style="margin-top:25px;">
						    			<input type="hidden" id ="no_intentos" name="no_intentos" value="<?=isset($cliente["no_intentos"]) ? $cliente["no_intentos"] : 1?>">
						    			<label for="no_intentos" id="intentos_completitud">Cantidad Intentos: <span class="label label-default" name='no_intentos'><?=isset($cliente["no_intentos"]) ? ($cliente["no_intentos"] <= 3 ? $cliente['no_intentos'] : 3) : 1?></span></label>
						    		</div>
				    			</div>
				    		</div>
				    		<div class="form-group col-md-12" id="observaciones_tipologias" style="display: none;">
				    			<label>Observaciones Tipologia:</label>
				    			<textarea name="observaciones_tipologia" class="form-control" style="resize:vertical; min-height:100px;" <?=($cliente["no_intentos"] >= 3) ? 'disabled' : '' ?>><?=$cliente["observaciones_tipologia"]?></textarea>
				    		</div>
				    	</div>
				    </div>
				  </div>
				</div>
			<?php endif; ?>

			<!-- INICIO RADICACION -->
			<div class="panel section-form">
			  <div class="panel-heading" role="tab" id="headingTwo" data-toggle="collapse" data-parent="#accordion" href="#inicio_radicacion" aria-expanded="true" aria-controls="collapseTwo">
			    <h4 class="panel-title">
			    <a class="collapsed" role="button">
			      <strong>INICIO RADICACIÓN</strong>
			    </a>
			  </h4>
			  </div>
			  <div id="inicio_radicacion" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingTwo">
			    <div class="panel-body">
					<div class="form-group">
						<label class="required-field" for="fecha_diligenciamiento">Fecha de diligenciamiento:</label>
                        <input type="date" id="fecha_diligenciamiento" name="fecha_diligenciamiento" class="form-control campo_obligatorio" value=<?=$InfoCliente['fecha_diligenciamiento']?> data-required="true" readonly="true" max=<?=(date("Y-m-d"))?> data-required="true">
						<small class="help-error-block"></small>
					</div>
					
					<?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6])):?>
				      	<div class="form-group" >
				     		<label class="required-field" for="ciudad_diligenciamiento">Ciudad de diligenciamiento:</label>
		                    <select name="ciudad_diligenciamiento" id="ciudad_diligenciamiento" class="form-control campo_obligatorio" data-required="true">
		                        <option value="">Seleccione ciudad...</option>
		                        <?php foreach($ciudades as $row):?>
		                            <option value="<?=$row['id']?>" <?=$cliente["ciudad_diligenciamiento"] == $row["id"] ? "selected" : ""?>><?=$row['nombre_ciudad']?></option>
		                        <?php endforeach;?>
		                    </select>
							<small class="help-error-block"></small>
				     	</div>
					    <div class="form-group" >
					    	<label for="sucursal">Sucursal:</label>
							<select name="sucursal" id="sucursal" class="form-control">
								<option value="">Seleccione sucursal...</option>
								<?php foreach($sucursal as $row):?>
									<option value="<?=$row['Sucursal']?>" <?= !empty($cliente['sucursal']) && strcasecmp($cliente["sucursal"], $row['Sucursal']) == 0 ? 'selected' : ''?>><?=$row['Sucursal']?></option>
								<?php endforeach;?>
							</select>
					    </div>
					    <div class="form-group" >
					    	<label for="tipo_solicitud" class="required-field">Tipo de solicitud:</label>
	                        <select name="tipo_solicitud" id="tipo_solicitud" class="form-control" data-required="true">
	                            <option value="">Seleccione tipo...</option>
	                            <option value="ACTUALIZACION" <?=$cliente["tipo_solicitud"] == "ACTUALIZACION" ? 'selected' : ''?>>ACTUALIZACION</option>
	                            <option value="RENOVACION" <?=$cliente["tipo_solicitud"] == "RENOVACION" ? 'selected' : ''?>>RENOVACION</option>
	                            <option value="VINCULACION" <?=$cliente["tipo_solicitud"] == "VINCULACION" ? 'selected' : ''?>>VINCULACION</option>
	                        </select>
					    </div>
					<?php endif; ?>
			    </div>
			  </div>
			</div>
			
			<?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6])):?>
				<!-- VINCULOS -->
				<div class="panel section-form" >
				  <div class="panel-heading" role="tab" id="headingThree" data-toggle="collapse" data-parent="#accordion" href="#vinculos" aria-expanded="true" aria-controls="collapseThree">
				    <h4 class="panel-title">
				    <a class="collapsed" role="button">
				      <strong>VINCULOS</strong>
				    </a>
				  </h4>
				  </div>
				  <div id="vinculos" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
				    <div class="panel-body">
				      	<div class="container-fluid">
				      		<div class="row content-radio-buttons" >
				      			<label for="clase_vinculacion" class="required-field title">Clase de vinculación:</label>
						      	<div class="form-group">
						      		<?php $pe_nat_vinculaciones = explode(",", $cliente["clase_vinculacion"]); ?>
						      		<?php $require_clase_vinculacion = 0; ?>
						      		<?php foreach($vinculaciones as $row):?>
						      			<div class="col-md-4">
						      				<input type="checkbox" name="clase_vinculacion[]" value="<?=$row['id']?>" class="radios" id="clase_vinculacion" <?= (in_array($row['id'], $pe_nat_vinculaciones)) ? 'checked' : '' ?> onclick="<?=($row["desc_vinculacion"] == "OTRO") ? "checkboxEnabledField(true,this,'div#clase_vinculacion_otra','hide')" : "javascript:void(0)"?>" <?php if($require_clase_vinculacion == 0) { echo 'data-required="true"' ; $require_clase_vinculacion++; } ?>><?= trim($row['desc_vinculacion']) ?>
									    </div>
			                        <?php endforeach;?>
						      	</div>
						      	<div id="clase_vinculacion_otra" class="form-group col-md-12" <?php if(is_null($cliente["clase_vinculacion_otro"])):?> style="display: none;" <?php endif;?>>
			                        <hr>
			                        <label>Otro, ¿Cuál?</label>
			                        <input type="text" name="clase_vinculacion_otro" class="form-control" value="<?=$cliente['clase_vinculacion_otro']?>">
						      	</div>
				      		</div>
				      		<div class="row content-radio-buttons" >
				      			<label for="relacion_tom_asegurado" class="required-field title">Relacion Tomador - Asegurado:</label>
			                    <div class="form-group">
			                    	<?php $pe_nat_rel_tom_aseg  = explode(",",$cliente["relacion_tom_asegurado"]);?>
			                    	<?php $require_relacion_tom_asegurado = 0; ?>
			                    	<?php foreach($relaciones as $row):?>
			                    	    <div class="col-md-4">
	                                        <input type="checkbox" name="relacion_tom_asegurado[]" value="<?=$row['id']?>" class="radios" id="relacion_tom_asegurado" <?= (in_array($row['id'],$pe_nat_rel_tom_aseg)) ? 'checked' : '' ?> onclick="<?=($row["desc_relacion"] == 'OTRA') ? "checkboxEnabledField(true,this,'div#relacion_tom_asegurado_otra','hide')" : "javascript:void(0)" ; ?>" <?php if($require_relacion_tom_asegurado == 0) { echo 'data-required="true"' ; $require_relacion_tom_asegurado++; } ?>><?= trim($row['desc_relacion'])?>
			                    	    </div>
			                    	<?php endforeach;?>
			                    </div>
			                    <div id="relacion_tom_asegurado_otra" class="form-group col-md-12" <?php if(is_null($cliente["relacion_tom_asegurado_otra"])):?> style="display: none;" <?php endif;?>>
			                        <hr>
			                        <label>Otro, ¿Cuál?</label>
			                        <input type="text" name="relacion_tom_asegurado_otra" class="form-control" value="<?=$cliente['relacion_tom_asegurado_otra']?>">
						      	</div>
				      			<hr>
				      		</div>
				      		<div class="row content-radio-buttons" >
				      			<label class="required-field title" for="relacion_tom_beneficiario">Relacion Tomador - Beneficiario:</label>
			                    <div class="form-group">
			                    	<?php $pe_nat_rel_tom_benef  = explode(",",$cliente["relacion_tom_beneficiario"]);?>
			                    	<?php $relacion_tom_beneficiario = 0; ?>
			                    	<?php foreach($relaciones as $row):?>
			                    	    <div class="col-md-4"> 
			                    	    	<input type="checkbox" name="relacion_tom_beneficiario[]" value="<?=$row['id']?>" class="radios" id="relacion_tom_beneficiario" <?= (in_array($row['id'],$pe_nat_rel_tom_benef)) ? 'checked' : '' ?> onclick="<?=($row["desc_relacion"] == 'OTRA') ? "checkboxEnabledField(true,this,'div#relacion_tom_beneficiario_otra','hide')" : "javascript:void(0)" ; ?>" <?php if($relacion_tom_beneficiario == 0) { echo 'data-required="true"' ; $relacion_tom_beneficiario++; } ?>><?= trim($row['desc_relacion']) ?>
			                    	    </div>
			                    	<?php endforeach;?>
			                    </div>
			                    <div id="relacion_tom_beneficiario_otra" class="form-group col-md-12" <?php if(is_null($cliente["clase_vinculacion_otro"])):?> style="display: none;" <?php endif;?>>
			                        <hr>
			                        <label>Otro, ¿Cuál?</label>
			                        <input type="text" name="relacion_tom_beneficiario_otra" class="form-control" value="<?=$cliente['relacion_tom_beneficiario_otra']?>">
						      	</div>
				      			<hr>
				      		</div>
				      		<div class="row content-radio-buttons" >
				      			<label class="required-field title" for="relacion_aseg_beneficiario" >Relacion Asegurado - Beneficiario:</label>
			                    <div class="form-group">
	                                <?php $pe_nat_rel_aseg_benef = explode(",",$cliente["relacion_aseg_beneficiario"]); ?>
	                                <?php $relacion_aseg_beneficiario = 0; ?>
			                    	<?php foreach($relaciones as $row):?>
			                    	    <div class="col-md-4">
	                                        <input type="checkbox" name="relacion_aseg_beneficiario[]" value="<?=$row['id']?>" class="radios" id="relacion_aseg_beneficiario" <?= (in_array($row['id'],$pe_nat_rel_aseg_benef)) ? 'checked' : '' ?> onclick="<?=($row["desc_relacion"] == 'OTRA') ? "checkboxEnabledField(true,this,'div#relacion_aseg_beneficiario_otra','hide')" : "javascript:void(0)" ; ?>" <?php if($relacion_aseg_beneficiario == 0) { echo 'data-required="true"' ; $relacion_aseg_beneficiario++; } ?>><?= trim($row['desc_relacion']) ?>
			                    	    </div>
			                    	<?php endforeach;?>
			                    </div>
			                    <div id="relacion_aseg_beneficiario_otra" class="form-group col-md-12" <?php if(is_null($cliente["clase_vinculacion_otro"])):?> style="display: none;" <?php endif;?>>
			                        <hr>
			                        <label>Otro, ¿Cuál?</label>
			                        <input type="text" name="relacion_aseg_beneficiario_otra" class="form-control" value="<?=$cliente['relacion_aseg_beneficiario_otra']?>">
						      	</div>
				      		</div>
				      	</div>
				    </div>
				  </div>
				</div>
			<?php endif; ?>
			
			<!-- DATOS PERSONALES -->
			<div class="panel section-form">
			  <div class="panel-heading" role="tab" id="headingThree">
			    <h4 class="panel-title">
			    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#datos_personales" aria-expanded="true" aria-controls="datos_personales">
			      <strong>DATOS PERSONALES</strong>
			    </a>
			  </h4>
			  </div>
			  <div id="datos_personales" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
			    <div class="panel-body">

				    <?php if(!in_array($InfoCliente['estado_formulario_id'],[6]) || (in_array($InfoCliente['estado_formulario_id'],[6]) && empty($cliente['primer_apellido']))): ?>
						<div class="form-group">
							<label class="required-field" for="primer_apellido">Primer apellido:</label>
							<input type="text" class="form-control campo_obligatorio" name="primer_apellido" id="primer_apellido" value="<?=$cliente['primer_apellido']?>"  onkeypress='OnlyLetters(this)' onkeyup='OnlyLetters(this)' <?php if (!in_array($InfoCliente['estado_formulario_id'],[5,6])): ?> data-required="true" <?php endif;?> >
							<small class="help-error-block"></small>
						</div>
					<?php endif; ?>

			    	<?php if(!in_array($InfoCliente['estado_formulario_id'],[6])): ?>
						<div class="form-group">
							<label for="segundo_apellido">Segundo apellido:</label>
							<input type="text" class="form-control" name="segundo_apellido" id="segundo_apellido" value="<?=$cliente['segundo_apellido']?>"  onkeypress='OnlyLetters(this)' onkeyup='OnlyLetters(this)' >
						</div>
					<?php endif; ?>

				    <?php if(!in_array($InfoCliente['estado_formulario_id'],[6]) || (in_array($InfoCliente['estado_formulario_id'],[6]) && empty($cliente['primer_nombre']))): ?>
						<div class="form-group">
							<label class="required-field" for="primer_nombre">Primer nombre:</label>
							<input class="form-control campo_obligatorio" type="text" name="primer_nombre" id="primer_nombre" value="<?=$cliente['primer_nombre']?>"  onkeypress='OnlyLetters(this)' onkeyup='OnlyLetters(this)' <?php if (!in_array($InfoCliente['estado_formulario_id'],[5,6])): ?> data-required="true" <?php endif;?>>
							<small class="help-error-block"></small>
						</div>
					<?php endif; ?>

			    	<?php if(!in_array($InfoCliente['estado_formulario_id'],[6])): ?>
						<div class="form-group">
							<label for="segundo_nombre">Segundo nombre:</label>
							<input class="form-control" type="text" name="segundo_nombre" id="segundo_nombre" value="<?=$cliente['segundo_nombre']?>"  onkeypress='OnlyLetters(this)' onkeyup='OnlyLetters(this)' >
						</div>
					<?php endif; ?>
			    	
					
					<div class="form-group">
						<label for="tipo_documento" class="required-field title">Tipo de documento:</label>
						<select class="form-control campo_obligatorio" name="tipo_documento" id="tipo_documento" <?= ($InfoCliente['tipo_documento'] != '') ? 'disabled="true"' : ''; ?>>
							<option value="">Seleccione un tipo de documento...</option>
							<?php foreach($natural as $row):?>
								<option type="radio" value="<?=$row['id']?>" <?=($InfoCliente['tipo_documento'] == $row['id']) ? 'selected' : '' ?>><?=$row['descripcion'] . " (" . $row['codigo'] . ")"?></option>
							<?php endforeach;?>
						</select>
						<small class="help-error-block"></small>
					</div>

					<div class="form-group">
	                    <label class="required-field" for="documento">Número de identificación:</label>
	                    <input type="text" class="form-control campo_obligatorio" name="documento" id="documento" <?php echo ($InfoCliente['documento'] != '') ? 'value="'.$InfoCliente['documento'].'" disabled="true"' :'value=""'; ?> data-required="true">
	                </div>

	                <?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6])):?>
		                <div class="col-md-12 content-radio-buttons" >
		                	<label class="required-field" for="sexo">Sexo:</label>
		                	<div class="form-group">
		                		<label class="radio-inline"><input type="radio" name="sexo" value="F" class="radios sexo campo_obligatorio" <?= ($cliente['sexo'] == "F") ? 'checked' : '' ?> data-required="true">F</label>
		                        <label class="radio-inline"><input type="radio" name="sexo" value="M" class="radios sexo" <?= ($cliente['sexo'] == "M") ? 'checked' : '' ?>>M</label>
		                        <label class="radio-inline"><input type="radio" name="sexo" class="radios sexo" value="" <?= (is_null($cliente['sexo'])) ? 'checked' : '' ?>>N/A</label>
								<small class="help-error-block"></small>
		                	</div>
		                </div>
		                <div class="col-md-12 content-radio-buttons" >
		                	<label class="required-field title" for="estado_civil">Estado civil:</label>
		                    <div class="form-group">
	                            <?php foreach($estado_civil as $row):?>
	                                <label class="radio-inline col-md-2">
	                                    <input type="radio" name="estado_civil" value="<?=$row['id']?>" class="radios estado_civil" <?= ($cliente['estado_civil'] == $row['id']) ? 'checked' : '' ?>><?= trim($row['desc_estado_civil'])?>
	                                </label>
	                            <?php endforeach;?>
	                            <label class="radio-inline"><input type="radio" name="estado_civil" class="radios estado_civil" value="" <?= (is_null($cliente['estado_civil'])) ? 'checked' : '' ?>>N/A</label>
		                    </div>
		                </div>
	                <?php endif; ?>
					
					<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[6]) && empty($cliente['fecha_expedicion_documento']))   || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
						<div class="form-group">
	                        <label class="required-field" for="fecha_expedicion_documento">Fecha de expedición documento:</label>
	                        <input type="date" name="fecha_expedicion_documento" id="fecha_expedicion_documento" class="form-control valida_anio" value="<?=$cliente['fecha_expedicion_documento']?>" max=<?=(date("Y-m-d"))?> <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?> onblur="habilitaFechaNacimiento(this, 'fecha_nacimiento')">
	                    	<small class="help-error-block"></small>
						</div>
	                <?php endif; ?>

						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['lugar_expedicion_documento']))   || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
	                    <div class="form-group">
		                    <label class="required-field" for="lugar_expedicion_documento">Lugar de expedición:</label>
		                    
							<select name="lugar_expedicion_documento" id="lugar_expedicion_documento" class="form-control" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?> onchange="validateOtro(this)">
	                            <option value="">Seleccione ciudad...</option>
	                            <?php foreach($ciudades as $row):?>
	                                <option value="<?=$row['nombre_ciudad']?>" <?= $cliente["lugar_expedicion_documento"] == $row['nombre_ciudad'] ? 'selected' : '' ?> ><?=$row['nombre_ciudad']?></option>
	                            <?php endforeach;?>
									<option value="Otro">Otro</option> 
	                        </select>
							<input type="text" class="form-control setValueOtro" name="txtLugar_expedicion_documento" id="txtLugar_expedicion_documento" placeholder="¿Cuál?" <?=(isset($cliente["lugar_expedicion_documento"]) && !(is_null($cliente["lugar_expedicion_documento"]))) ? 'value="'.$cliente["lugar_expedicion_documento"].'" data-valorselect="true" style="display: block"' : '' ?>>
		                </div>
		            <?php endif; ?>

						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['fecha_nacimiento']))   || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
	                    <div class="form-group">
	                        <label class="required-field" for="fecha_nacimiento">Fecha de nacimiento:</label>
	                        <input type="date" name="fecha_nacimiento" id="fecha_nacimiento"  class="form-control" value="<?=$cliente['fecha_nacimiento']?>"  max=<?=(date("Y-m-d"))?> <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?> onblur="validaFechaNacimiento(this, 'fecha_expedicion_documento')">
							<small class="help-error-block"></small>
	                    </div>
	                <?php endif; ?>

						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['lugar_nacimiento']))   || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
						<div class="form-group">
							<label class="required-field" for="lugar_nacimiento">Lugar de nacimiento:</label>	
							<select name="lugar_nacimiento" id="lugar_nacimiento" class="form-control" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?> onchange="validateOtro(this)">
								<option value="">Seleccione ciudad...</option>
								<?php foreach($ciudades as $row):?>
									<option value="<?=$row['nombre_ciudad']?>" <?= $cliente["lugar_nacimiento"] == $row['nombre_ciudad'] ? 'selected' : ''?> ><?=$row['nombre_ciudad']?></option>
								<?php endforeach;?>
								<option value="Otro">Otro</option>
							</select>
							<input type="text" class="form-control setValueOtro" name="txtLugarNacimiento" id="txtLugarNacimiento" placeholder="¿Cuál?" <?=(isset($cliente["lugar_nacimiento"]) && !(is_null($cliente["lugar_nacimiento"]))) ? 'value="'.$cliente["lugar_nacimiento"].'" data-valorselect="true" style="display: block"' : '' ?>>
						</div>
					<?php endif; ?>

						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['nacionalidad_1']))   || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
						<div class="form-group">
	                        <label class="required-field" for="nacionalidad_1">Nacionalidad 1:</label>
	                        <select name="nacionalidad_1" id="nacionalidad_1" class="form-control" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?>>
	                            <option value="">Seleccione país...</option>
	                            <?php foreach($paises as $row):?>
	                                <option value="<?=$row['id']?>" <?= $cliente["nacionalidad_1"] == $row['id'] ? 'selected' : ''?> ><?=$row['nombre_pais']?></option>
	                            <?php endforeach;?>
	                        </select>
	                    </div>
	                <?php endif; ?>

                    <?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6])):?>
	                    <div class="form-group">
	                        <label for="nacionalidad_2">Nacionalidad 2:</label>
	                        <select name="nacionalidad_2" id="nacionalidad_2" class="form-control" data-required="true">
	                            <option value="">Seleccione país...</option>
	                            <?php foreach($paises as $row):?>
	                                <option value="<?=$row['id']?>" <?= $cliente["nacionalidad_2"] == $row['id'] ? 'selected' : ''?> ><?=$row['nombre_pais']?></option>
	                            <?php endforeach;?>
	                        </select>
	                    </div>
		                <?php endif; ?>
						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['ocupacion']))   || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
		                    <div class="form-group">
		                        <label class="required-field" for="ocupacion">Ocupación:</label>
							<select name="ocupacion" id="ocupacion" class="form-control" data-required="true" onchange="validateOtro(this)">
								<option value="">Seleccione ocupación...</option>
								<?php foreach($ocupaciones as $row):?>
									<option value="<?=$row['descripcion']?>" <?= $cliente["ocupacion"] == $row['descripcion'] ? 'selected' : ''?> ><?=$row['descripcion']?></option>
								<?php endforeach;?>
								<option value="Otro">Otro</option>
							</select>
							<input type="text" class="form-control setValueOtro" name="txtOcupacion" id="txtOcupacion" placeholder="¿Cuál?" <?=(isset($cliente["ocupacion"]) && !(is_null($cliente["ocupacion"]))) ? 'value="'.$cliente["ocupacion"].'" data-valorselect="true" style="display: block"' : '' ?>>
						</div>
		                <?php endif; ?>
						
						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['direccion_residencia']))  || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
	                    <label class="required-field" for="direccion_residencia">Dirección residencia:</label>
						<div class="direccion" id='div_direccion_residencia_natural'>
							<div class="containerDireccion">
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
									<select class="form-control">
										<option value="">Seleccione via...</option>
										<?php foreach($vias as $row):?>
											<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-1">
									<input type="text" class="form-control" placeholder="0">
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
									<select class="form-control">
										<option value="">Literal...</option>
										<?php foreach($literales as $row):?>
											<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
									<select class="form-control">
										<option value="">Orientacion...</option>
										<?php foreach($orientacion as $row):?>
											<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-1">
									<input type="text" class="form-control" placeholder="0">
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
									<select class="form-control">
										<option value="">Literal...</option>
										<?php foreach($literales as $row):?>
											<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
									<select class="form-control">
										<option value="">Orientacion...</option> 
										<?php foreach($orientacion as $row):?>
											<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-1">
									<input type="text" class="form-control" placeholder="0">
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
									<select class="form-control">
										<option value="">Seleccione predio...</option>
										<?php foreach($detallePredio as $row):?>
											<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-1">
									<input type="text" class="form-control" placeholder="0">
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
									<select class="form-control">
										<option value="">Seleccione predio...</option>
										<?php foreach($detallePredio as $row):?>
											<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-1">
									<input type="text" class="form-control" placeholder="0">
								</div>
								<div class="controlDireccion col col-sm-2 col-md-3 col-lg-5">
									<select class="form-control">
										<option value="">Seleccione predio...</option>
										<?php foreach($detallePredio as $row):?>
											<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="controlDireccion col col-sm-10 col-md-9 col-lg-12">
									<input type="text" name="detalle_direccion" class="form-control" placeholder="Detalles">
								</div>
							</div>
						</div>
						<div class="divHabilitaDireccion">
							<input type="checkbox" value="Habilitar campo" onclick="habilitaControlesDireccion(this)"><label for="value" class="checkDireccion">No Estándar</label>
						</div>
						<div class="form-group">
							<input type="text" name="direccion_residencia" readonly="readonly" id="direccion_residencia" class="form-control" value="<?=$cliente['direccion_residencia']?>"  <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?> >
						</div>
					<?php endif; ?>

						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['departamento_residencia']))   || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
						<div class="form-group">
	                        <label class="required-field" for="departamento_residencia">Departamento residencia:</label>
	                        <select name="departamento_residencia" id="departamento_residencia" class="form-control" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?> > 
	                            <option value="">Seleccione departamento...</option>
	                            <?php foreach($departamentos as $row):?>
	                                <option value="<?=$row['id']?>"  <?= $cliente['departamento_residencia'] == $row['id'] ?  'selected' : '' ?> ><?=$row['nombre_departamento']?></option>
	                            <?php endforeach;?>
	                        </select>
	                    </div>
	                <?php endif; ?>

						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['ciudad_residencia']))  || (in_array($InfoCliente['estado_formulario_id'],[5]) ) ): ?>
		                    <div class="form-group">
		                        <label  class="required-field" for="ciudad_residencia">Ciudad residencia:</label>
	                        <select name="ciudad_residencia" id="ciudad_residencia" class="form-control campo_obligatorio" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?> >
	                            <option value="">Seleccione una ciudad...</option>   
		                            <?php foreach($ciudades as $row):?>
		                                <option value="<?=$row['id']?>"  <?= $cliente['ciudad_residencia'] == $row['id'] ?  'selected' : '' ?> ><?=$row['nombre_ciudad']?></option>
		                            <?php endforeach;?>                         
		                        </select>
							<small class="help-error-block"></small>
	                    </div>
		                <?php endif; ?>

						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || in_array($InfoCliente['estado_formulario_id'],[5]) ): ?>
						<div class="form-group">
	                        <label for="telefono">Teléfono:</label>
	                        <input type="tel" name="telefono" id="telefono" placeholder="Ingrese numero de telefono Min: 7 digitos" class="form-control tel" value="<?=$cliente['telefono']?>" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?>>
	                        <small class="help-error-block"></small>
	                    </div>
	                <?php endif; ?>

						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['celular']))   || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
	                    <div class="form-group">
	                        <label class="required-field" for="celular">Celular:</label>
	                        <input type="tel" name="celular" id="celular" class="form-control cel" value="<?=$cliente['celular']?>" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?> >
	                        <small class="help-error-block"></small>
	                    </div>
	                <?php endif; ?>
						
						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['correo_electronico']))   || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
	                    <div class="form-group">
	                        <label for="correo_electronico">Correo electrónico:</label>
	                        <input type="email" name="correo_electronico" id="correo_electronico" class="form-control" value="<?=$cliente['correo_electronico']?>" data-required="true" onchange="ValidateEmail(this)">
	                    </div>
		               	<?php endif; ?>

						<?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])  || (in_array($InfoCliente['estado_formulario_id'],[5,6]) && empty($cliente['actividad_eco_principal']))   || (in_array($InfoCliente['estado_formulario_id'],[5]) )): ?>
	                    <div class="form-group">
	                    	<label class="required-field title" for="actividad_eco_principal">Actividad Principal:</label>
							<select name="actividad_eco_principal" id="actividad_eco_principal" class="select2 campo_obligatorio" data-required="true">
	                            <option value=""></option>   
	                            <?php foreach($actividades_principales as $row):?>
	                                <option value="<?=$row['id']?>"  <?=$cliente['actividad_eco_principal'] === $row['id'] ?  'selected' : '' ?>><?=$row['nombre_actividad_principal']?></option>
	                            <?php endforeach;?>                         
	                        </select>
							<small class="help-error-block"></small>
	                    </div>
						<div id="actividad_eco_principal_otra" class="form-group" <?=($cliente['actividad_eco_principal'] != 2222) ? 'style="display: none;"' : '';?>>
	                        <label>Especifique, ¿Cuál?:</label>
	                        <input type="text" name="actividad_eco_principal_otra" id="actividad_eco_principal_otra" class="form-control" value="<?=$cliente['actividad_eco_principal_otra']?>" >
	                    </div>
		                <div class="form-group">
	                        <label for="ciiu_cod">CIIU(Cod):</label>
	                        <input type="text" name="ciiu_cod" id="ciiu_cod" class="form-control campo_obligatorio" value="<?=$cliente['ciiu_cod']?>" min='0'  data-required="true">
							<small class="help-error-block"></small>
	                    </div>
	                    <hr>
		                <?php endif; ?>

		                <?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6])):?>
		                <div class="form-group">
	                		<label class="title">Actividad Principal Secundaria:</label>
	                		<select name="actividad_secundaria" id="actividad_secundaria" class="select2" data-required="true">
	                            <option value=""></option>   
	                            <?php foreach($actividades_principales as $row):?>
	                                <option value="<?=$row['id']?>"  <?=$cliente['actividad_secundaria'] == $row['id'] ?  'selected' : '' ?>><?=$row['nombre_actividad_principal']?></option>
	                            <?php endforeach;?>                         
	                        </select>
	                	</div>
							<div class="form-group">
		                        <label for="ciiu_secundario">CIIU Secundario:</label>
		                        <input type="text" class="form-control" name="ciiu_secundario" id="ciiu_secundario" value="<?=$cliente['ciiu_secundario']?>" data-required="true">
		                    </div>
			            <?php endif; ?>
			            <?php if(!in_array($InfoCliente["estado_formulario_id"],[6]) || (in_array($InfoCliente["estado_formulario_id"],[6]) && $cliente['trabaja_actualmente'] == 1 && (empty($cliente['trabaja_actualmente']) || empty($cliente['direccion_empresa']) || empty($cliente['departamento_empresa']) || empty($cliente['ciudad_empresa'])))): ?>
							<div class="col-md-12 from-group">
		                	<label for="datos_trabajo" class="required-field">Presenta información de la empresa ? </label>
			                	<label class="radio-inline"><input type="radio" name='trabaja_actualmente' value="1" <?=($cliente['trabaja_actualmente'] == "1") ? 'checked' : ''; ?> data-required="true">Si</label>
			                	<label class="radio-inline"><input type="radio" name='trabaja_actualmente' value="0" <?=($cliente['trabaja_actualmente'] === "0") ? 'checked' : ''; ?> onclick="checkboxEnabledField(false,this,'div#datos_empresa_natural','hide')">No</label>
							<small class="help-error-block"></small>
		                </div>
		            <?php endif; ?>
			    </div>
			  </div>
			</div>
	
			<?php if(!in_array($InfoCliente["estado_formulario_id"],[6]) || (in_array($InfoCliente["estado_formulario_id"],[6]) && $cliente['trabaja_actualmente'] == 1)):?>
				<!-- DATOS DE LA EMPRESA DONDE TRABAJA -->
				<div class="panel section-form"  id="datos_empresa_natural" <?=($cliente['trabaja_actualmente'] == 0) ? 'style="display:none"' : '' ?>>
				  <div class="panel-heading" role="tab" id="headingThree">
				    <h4 class="panel-title">
				    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#datos_empresa" aria-expanded="true" aria-controls="collapseThree">
				      <strong>DATOS EMPRESA DONDE TRABAJA</strong>
				    </a>
				  </h4>
				  </div>
				  <div id="datos_empresa" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
				    <div class="panel-body">

				    	<?php if(!in_array($InfoCliente["estado_formulario_id"],[6])):?>
	                    <div class="form-group">
	                        <label class="required-field" for="sector">Sector:</label>
	                        <select name="sector" id="sector" class="form-control campo_obligatorio" data-required="true">
	                            <option value="">Seleccione un sector...</option>
	                            <?php foreach($sectores as $row):?>
	                                <option value="<?=$row['id']?>" <?= $cliente['sector'] == $row['id'] ? 'selected' : '' ?>><?=$row['desc_sector']?></option>
	                            <?php endforeach;?>
	                        </select>
							<small class="help-error-block"></small>
	                    </div>
	                    <div class="col-md-12 content-radio-buttons">
	                    	<label for="tipo_actividad" class="title required-field">Tipo de actividad:</label>
	                    	<div class="form-group">
	                    		<?php foreach($tipos_actividades as $row):?>
			                        <div class="col-md-6">
				                            </label class="radio-inline"><input type="radio" name="tipo_actividad" value="<?=$row['id']?>" class="radios tipo_actividad" <?= ($cliente['tipo_actividad'] == $row['id']) ? 'checked' : '' ?> onclick="checkboxEnabledField(<?=json_encode($row['id'] == 16)?>,this,'div#tipo_actividad_otro','hide')"><?= trim($row['nombre_tipo_actividad'])?></label>
			                        </div>
			                    <?php endforeach;?>
								<small class="help-error-block"></small>
	                    	</div>
	                    </div>
	                    <div class="form-group" id="tipo_actividad_otro" <?php if(is_null($cliente['tipo_actividad_otro']) && $cliente['tipo_actividad'] != 16):?> style="display: none;" <?php endif;?>>
		                    <label>Otro, ¿Cuál?</label>
		                    <input type="text" name="tipo_actividad_otro" id="tipo_actividad_otro" value="<?=$cliente['tipo_actividad_otro']?>" class="form-control">
	                    </div>                    
	                    <div class="form-group">
	                        <label class="required-field" for="cargo">Cargo:</label>
	                        <input type="text" name="cargo" id="cargo" class="form-control" value="<?=$cliente['cargo']?>" data-required="true">
	                    </div>
	                    <hr>
		                <?php endif;?>

	                    <?php if(!in_array($InfoCliente["estado_formulario_id"],[6]) || (in_array($InfoCliente["estado_formulario_id"],[6]) && empty($cliente['empresa_donde_trabaja']))):?>
	                    <div class="form-group">
	                        <label class="required-field" for="empresa_donde_trabaja">Empresa donde trabaja:</label>
	                        <input type="text" name="empresa_donde_trabaja" id="empresa_donde_trabaja" class="form-control" value="<?=$cliente['empresa_donde_trabaja']?>"  data-required="true">
	                    </div>
	                    <?php endif;?>
	                    <?php if(!in_array($InfoCliente["estado_formulario_id"],[6]) || (in_array($InfoCliente["estado_formulario_id"],[6]) && empty($cliente['direccion_empresa']))):?>
	                    <div class="form-group">
	                        <label class="required-field" for="direccion_empresa">Dirección empresa donde trabaja:</label>
							<div class="direccion" id='div_direccion_empresa'>
								<div class="containerDireccion">
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
										<select class="form-control">
											<option value="">Seleccione via...</option>
											<?php foreach($vias as $row):?>
												<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
											<?php endforeach;?>
										</select>
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-1">
										<input type="text" class="form-control" placeholder="0">
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
										<select class="form-control">
											<option value="">Literal...</option>
											<?php foreach($literales as $row):?>
												<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
											<?php endforeach;?>
										</select>
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
										<select class="form-control">
											<option value="">Orientacion...</option>
											<?php foreach($orientacion as $row):?>
												<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
											<?php endforeach;?>
										</select>
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-1">
										<input type="text" class="form-control" placeholder="0">
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
										<select class="form-control">
											<option value="">Literal...</option>
											<?php foreach($literales as $row):?>
												<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
											<?php endforeach;?>
										</select>
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
										<select class="form-control">
											<option value="">Orientacion...</option> 
											<?php foreach($orientacion as $row):?>
												<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
											<?php endforeach;?>
										</select>
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-1">
										<input type="text" class="form-control" placeholder="0">
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
										<select class="form-control">
											<option value="">Seleccione predio...</option>
											<?php foreach($detallePredio as $row):?>
												<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
											<?php endforeach;?>
										</select>
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-1">
										<input type="text" class="form-control" placeholder="0">
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-2">
										<select class="form-control">
											<option value="">Seleccione predio...</option>
											<?php foreach($detallePredio as $row):?>
												<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
											<?php endforeach;?>
										</select>
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-1">
										<input type="text" class="form-control" placeholder="0">
									</div>
									<div class="controlDireccion col col-sm-2 col-md-3 col-lg-5">
										<select class="form-control">
											<option value="">Seleccione predio...</option>
											<?php foreach($detallePredio as $row):?>
												<option value="<?=$row['valor_uno']?>"><?=$row['valor_uno']?></option>
											<?php endforeach;?>
										</select>
									</div>
									<div class="controlDireccion col col-sm-10 col-md-9 col-lg-12">
										<input type="text" name="detalle_direccion" class="form-control" placeholder="Detalles">
									</div>
								</div>
							</div>
							<div class="divHabilitaDireccion">
								<input type="checkbox" value="Habilitar campo" onclick="habilitaControlesDireccion(this)"><label for="value" class="checkDireccion">No Estándar</label>
							</div>
							<div class="form-group">
	                        	<input type="text" name="direccion_empresa" id="direccion_empresa" readonly="readonly" class="form-control" value="<?=$cliente['direccion_empresa']?>" data-required="true">
		                    </div>
	                    </div>
	                    <hr>
		                <?php endif;?>
	                    <?php if(!in_array($InfoCliente["estado_formulario_id"],[6]) || (in_array($InfoCliente["estado_formulario_id"],[6]) && empty($cliente['departamento_empresa']))):?>
	                    <div class="form-group">
	                        <label class="required-field" for="departamento_empresa">Departamento empresa:</label>
	                        <select name="departamento_empresa" id="departamento_empresa" class="form-control" data-required="true">
	                            <option value="">Seleccione departamento...</option>
	                            <?php foreach($departamentos as $row):?>
	                                <option value="<?=$row['id']?>"  <?= $cliente['departamento_empresa'] == $row['id'] ?  'selected' : '' ?> ><?=$row['nombre_departamento']?></option>
	                            <?php endforeach;?>
	                        </select>
	                    </div>
		                <?php endif;?>
	                    <?php if(!in_array($InfoCliente["estado_formulario_id"],[6]) || (in_array($InfoCliente["estado_formulario_id"],[6]) && empty($cliente['ciudad_empresa']))):?>
	                    <div class="form-group">             
	                        <label  class="required-field" for="ciudad_empresa">Ciudad empresa:</label>
	                        <select name="ciudad_empresa" id="ciudad_empresa" class="form-control" data-required="true">
	                            <option value="">Seleccione ciudad...</option>   
	                            <?php foreach($ciudades as $row):?>
	                                <option value="<?=$row['id']?>"  <?= $cliente['ciudad_empresa'] == $row['id'] ?  'selected' : '' ?> ><?=$row['nombre_ciudad']?></option>
	                            <?php endforeach;?>                         
	                        </select>
	                    </div>
		                <?php endif;?>
	                    <?php if(!in_array($InfoCliente["estado_formulario_id"],[6])):?>
	                    <div class="form-group">
	                        <label class="required-field" for="telefono_empresa">Teléfono empresa:</label>
	                        <input type="tel" name="telefono_empresa" id="telefono_empresa" class="form-control tel" value="<?=$cliente['telefono_empresa']?>" data-required="true" onkeypress="OnlyNumbers(this)">
							<small class="help-error-block"></small>
	                    </div>
	                    <?php endif;?>
	                    <?php if(!in_array($InfoCliente["estado_formulario_id"],[6])):?>
		                    <div class="form-group">
		                        <label class="required-field" for="fax">Fax empresa:</label>
	                        <input type="text" name="fax" id="fax" class="form-control" value="<?=$cliente['fax_empresa']?>" data-required="true" onkeypress="OnlyNumbers(this)">
								<small class="help-error-block"></small>
		                    </div>
	                    <?php endif;?>
				    </div>
				  </div>
				</div>
			<?php endif; ?>

			<?php if(!in_array($InfoCliente['estado_formulario_id'],[6,5]) || (in_array($InfoCliente['estado_formulario_id'],[6]) && $cliente['ingresos'] == "" || $cliente['egresos'] == "" || $cliente['activos'] == "" || $cliente['pasivos'] == "" || $cliente['patrimonio'] == "")): ?>
                <!-- INFORMACION FINANCIERA -->
                <div class="panel section-form">
                  <div class="panel-heading" role="tab" id="headingThree">
                    <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#informacion_financiera" aria-expanded="true" aria-controls="collapseThree">
                      <strong>INFORMACIÓN FINANCIERA</strong>
                    </a>
                  </h4>
                  </div>
                  <div id="informacion_financiera" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                    <div class="panel-body">
                        
                        <?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6]) || (in_array($InfoCliente["estado_formulario_id"],[6,5]) && $cliente['ingresos'] == "")): ?>
				      	<div class="form-group col-md-6">
	                        <label class="required-field" for="ingresos">Ingresos:</label>
                                <input type="text" class="currency form-control" name="ingresos" id="ingresos" value="<?=$cliente['ingresos'];?>" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?>>
                            </div>
                        <?php endif; ?>
                        
                        <?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6]) || (in_array($InfoCliente["estado_formulario_id"],[6,5]) && $cliente['egresos'] == "")): ?>
	                    <div class="form-group col-md-6">
	                        <label class="required-field" for="egresos">Egresos:</label>
                                <input type="text" class="currency form-control" name="egresos" id="egresos" value="<?=$cliente['egresos'];?>" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?>>
                            </div>
                            <hr>
                        <?php endif; ?>
                        
                        <?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6]) || (in_array($InfoCliente["estado_formulario_id"],[6,5]) && $cliente['activos'] == "")): ?>
						<div class="form-group col-md-6">
	                        <label class="required-field" for="activos">Activos:</label>
                                <input type="text" class="currency form-control" name="activos" id="activos" value="<?=$cliente['activos'];?>" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?>>
                            </div>
                        <?php endif; ?>

                        <?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6]) || (in_array($InfoCliente["estado_formulario_id"],[6,5]) && $cliente['pasivos'] == "")): ?>
	                    <div class="form-group col-md-6">
	                        <label class="required-field" for="pasivos">Pasivos:</label>
                                <input type="text" class="currency form-control" name="pasivos" id="pasivos" value="<?=$cliente['pasivos'];?>" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?>>
                            </div>
                            <hr>
                        <?php endif; ?>

                        <?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6]) || (in_array($InfoCliente["estado_formulario_id"],[6,5]) && $cliente['patrimonio'] == "")): ?>
                            <div class="form-group col-md-6">
                                <label for="patrimonio" class="required-field">Patrimonio:</label>
                                <input type="text" class="currency form-control" name="patrimonio" id="patrimonio" value="<?=$cliente['patrimonio'];?>" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?>>
                            </div>
                            <hr>
                        <?php endif; ?>

                        <?php if((!in_array($InfoCliente["estado_formulario_id"],[5,6]))): ?>
                            <div class="form-group col-md-6">
                                <label for="otros_ingresos" class="required-field">Otros ingresos:</label>
                                <input type="text" class="currency form-control" name="otros_ingresos" id="otros_ingresos" value="<?=$cliente['otros_ingresos'];?>" data-required="true">
                            </div>
                        <?php endif; ?>

                        <?php if((!in_array($InfoCliente["estado_formulario_id"],[5,6]))): ?>
							<div class="form-group col-md-12">
								<label class="required-field" for="desc_otros_ingresos">Concepto otros ingresos:</label>
								<input class="form-control onlytext" type="text" name="desc_otros_ingresos" id="desc_otros_ingresos" value="<?=$cliente['desc_otros_ingresos']?>"  data-required="true">
							</div>
						<?php endif; ?>
						<?php if((!in_array($InfoCliente["estado_formulario_id"],[5,6]))): ?>
							<div class="form-group col-md-12"> 
								<label class="required-field" for="tipo_moneda">Tipo moneda:</label>
								<select class="form-control" name="tipo_moneda" id="tipo_moneda">
									<option value="">Seleccione una moneda...</option>
									<?php foreach($monedas as $row):?>
										<option type="radio" value="<?=$row['Descripcion']?>" <?= $cliente['tipo_moneda'] == $row['Descripcion'] ? 'selected' : '' ?>><?=$row['Descripcion'] . " (" . $row['Codigo'] . ")" ?></option>
									<?php endforeach;?>
								</select>
							</div>
                        <?php endif; ?>
                    </div>
                  </div>
                </div>
			<?php endif; ?>

			<?php if(!in_array($InfoCliente["estado_formulario_id"],[6,5]) || (in_array($InfoCliente["estado_formulario_id"],[6]) && $cliente["anexo_preguntas_ppes"] == 1 && isset($anexo_ppes) && empty($anexo_ppes))):?>
				<!-- PREGUNTAS PPES -->
				<div class="panel section-form">
				  <div class="panel-heading" role="tab" id="headingThree">
				    <h4 class="panel-title">
				    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#preguntas_ppes" aria-expanded="true" aria-controls="collapseThree">
				      <strong>PREGUNTAS PPES</strong>
				    </a>
				  </h4>
				  </div>
				  <div id="preguntas_ppes" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
				    <div class="panel-body">
						
					    	<!-- PREGUNTA 1 -->
		                    <div class="col-md-12 content-radio-buttons">
		                        <label for="persona_publica" class="title required-field">¿Es usted una persona publicamente expuesta?:</label>
		                        <div class="form-group">                          
		                            <label class="radio-inline"><input type="radio" name="persona_publica" value="SI" <?=($cliente["persona_publica"] == "SI") ? "checked" : ""; ?> class="radios persona_publica anexo_ppes campo_obligatorio" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?>>Si</label>
									<label class="radio-inline"><input type="radio" name="persona_publica" value="NO" <?=($cliente["persona_publica"] == "NO") ? "checked" : ""; ?> class="radios persona_publica anexo_ppes">No</label>
		                            <label class="radio-inline"><input type="radio" name="persona_publica" value="VACIO" <?=($cliente["persona_publica"] == "VACIO") ? "checked" : ""; ?> class="radios persona_publica anexo_ppes">N/A</label>
									<small class="help-error-block"></small>
		                        </div>
		                    </div>

							<!-- PREGUNTA 2 -->
		                    <div class="col-md-12 content-radio-buttons">
		                        <label for="vinculo_persona_publica" class="title required-field">¿Existe algún vinculo entre usted y una persona considerada publicamente expuesta?:</label>
		                        <div class="form-group">
		                            <label class="radio-inline">
		                                <input type="radio" name="vinculo_persona_publica" value="SI" class="radios vinculo_persona_publica anexo_ppes campo_obligatorio" <?=($cliente['vinculo_persona_publica'] == "SI") ? 'checked' : '' ?> onclick="checkboxEnabledField(true,this,'div#anexo-box','hide')" <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?> >Si
		                            </label>
		                            <label class="radio-inline">
		                                <input type="radio" name="vinculo_persona_publica" value="NO" class="radios vinculo_persona_publica anexo_ppes" <?=($cliente['vinculo_persona_publica'] == "NO") ? 'checked' : '' ?> onclick="checkboxEnabledField(false,this,'div#anexo-box','hide')">No
		                            </label>
		                            <label class="radio-inline">
		                            	<input type="radio" name="vinculo_persona_publica" class="radios vinculo_persona_publica anexo_ppes" value="VACIO" <?= ($cliente['vinculo_persona_publica'] == "VACIO") ? 'checked' : '' ?>>N/A
		                            </label>
									<small class="help-error-block"></small>
		                        </div>
		                    </div> 
						
						<?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6])):?>
							<!-- PREGUNTA 3 -->
		                    <div class="col-md-12 content-radio-buttons">
		                        <label for="productos_publicos" class="title required-field">¿Por su cargo o actividad administra recursos publicos?:</label>
		                        <div class="form-group">                           
		                            <label class="radio-inline">
		                                <input type="radio" name="productos_publicos" value="SI" class="radios productos_publicos anexo_ppes campo_obligatorio" <?= ($cliente['productos_publicos'] == "SI") ? 'checked' : '' ?> <?php if(!in_array($InfoCliente['estado_formulario_id'],[5,6])):?> data-required="true" <?php endif;?> >Si
		                            </label>
		                            <label class="radio-inline">
		                                <input type="radio" name="productos_publicos" value="NO" class="radios productos_publicos anexo_ppes" <?= ($cliente['productos_publicos'] == "NO") ? 'checked' : '' ?>>No
		                            </label>
		                            <label class="radio-inline">
		                            	<input type="radio" name="productos_publicos" value="VACIO" class="radios productos_publicos anexo_ppes" <?= ($cliente['productos_publicos'] == "VACIO") ? 'checked' : '' ?>>N/A
		                            </label>
									<small class="help-error-block"></small>
		                        </div>
		                    </div>
						
		                    <!-- PREGUNTA 4 -->
		                    <div class="col-md-12 content-radio-buttons">
		                        <label for="obligaciones_tributarias_otro_pais" class="title required-field">¿Es usted sujeto de obligaciones tributarias en otro pais o grupo de paises ? :</label>
		                        <div class="form-group" desc="true">
		                            <label class="radio-inline">
		                                <input type="radio" name="obligaciones_tributarias_otro_pais" data-required="true" value="SI" class="radios obligaciones_tributarias_otro_pais campo_obligatorio" <?= ($cliente['obligaciones_tributarias_otro_pais'] == "SI") ? 'checked' : '' ?> onclick="checkboxEnabledField(true,this,'div#obligaciones_tributarias_otro_pais','hide')">Si
		                            </label>
		                            <label class="radio-inline">
		                                <input type="radio" name="obligaciones_tributarias_otro_pais" value="NO" class="radios obligaciones_tributarias_otro_pais" <?= ($cliente['obligaciones_tributarias_otro_pais'] == "NO") ? 'checked' : '' ?> onclick="checkboxEnabledField(false,this,'div#obligaciones_tributarias_otro_pais','hide')">No
		                            </label>
		                            <label class="radio-inline">
		                            	<input type="radio" name="obligaciones_tributarias_otro_pais" class="radios obligaciones_tributarias_otro_pais" value="VACIO" <?=($cliente['obligaciones_tributarias_otro_pais'] == "VACIO") ? 'checked' : '' ?>>N/A
		                            </label>
									<small class="help-error-block"></small>
		                        </div>
		                    </div>
		                    <div class="col-md-12 form-group" <?php if(!is_null($cliente['desc_obligaciones_tributarias_otro_pais'] || $cliente['obligaciones_tributarias_otro_pais'] == "SI")):?> style="display: none;" <?php endif;?> id="obligaciones_tributarias_otro_pais">
		                        <label>Si, indique</label>
		                        <input type="text" class="form-control" name="desc_obligaciones_tributarias_otro_pais" id="desc_obligaciones_tributarias_otro_pais" value="<?=$cliente['desc_obligaciones_tributarias_otro_pais']?>">
		                        <hr>
		                    </div>
		                <?php endif; ?>
						

						<!-- ANEXO PREGUNTAS PPES -->
		                    <div class="col-md-12 content-radio-buttons" id="btn_anexo_preguntas_ppes" <?=($cliente["anexo_preguntas_ppes"] != 1 && $cliente["persona_publica"] != "SI" && $cliente['vinculo_persona_publica'] != "SI" && $cliente['productos_publicos'] != "SI" && $cliente['obligaciones_tributarias_otro_pais'] != "Si") ? 'style="display: none"' : ""; ?>>
		                        <div class="form-group">
			                        <label class="control-label title">Anexo preguntas <strong>PPE:</strong></label>
			                    	<input type="hidden" name="anexo_preguntas_ppes" value="0">
		                            <label class="radio-inline" id="add_preguntas_rep_legal" ><button type="button" class="btn btn-sm btn-success" onclick="$('div#anexo_preguntas_ppes').modal('show')">AGREGAR <small class="glyphicon glyphicon-plus"></small></button></label>
		                        </div>
		                    </div>
		   
	                    <!-- MODAL PREGUNTAS PPES  -->
	                    <div class="modal fade" id="anexo_preguntas_ppes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
	                        <div class="modal-dialog" style="width:90%;">
	                            <div class="modal-content">
	                                <div class="modal-header">
	                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
	                                  <h4 class="modal-title" style="font-size: 20px !important;">Diligencie el siguiente cuadro</h4>
	                                </div>
	                                <div class="modal-body">
	                                    <div class="table-responsive">
	                                        <table class="table table-hover table-bordered" id="table_ppes_pe_publica" style="width: 1260px !important; ">
	                                            <thead>
	                                                <tr class="bg-primary">
	                                                    <th colspan="8" class="text-center">
	                                                        <span class="pull-left" style="margin-top: 5px;">Preguntas Anexo PPES</span>
	                                                    </th>
	                                                </tr>
	                                                <tr>
	                                                    <th>vinculo/relacion*</th>
	                                                    <th>Nombre</th>
	                                                    <th>Tipo de identificación</th>
	                                                    <th>No de identificación</th>
	                                                    <th width="12%">Nacionalidad</th>
	                                                    <th>Entidad</th>
	                                                    <th>Cargo</th>
	                                                    <th>Fecha Desviculacion</th>
	                                                </tr>
	                                            </thead>
	                                            <tbody>
		                                            <?php $contAnexos_ppes = 0; ?>
	                                            	<?php if(isset($anexos_ppes)): ?>
		                                                <?php foreach($anexos_ppes as $keyAnexos_ppes => $valuesAnexos_ppes):$contAnexos_ppes++;?>
		                                                    <tr>
		                                                        <th class="hidden">
		                                                            <input type="hidden" name="anexos_cliente[<?=$contAnexos_ppes?>][anexo_id]" value="<?=$valuesAnexos_ppes["id"]?>">
		                                                        </th>
		                                                        <th>
																	<select class="form-control add_anexos_ppes" name="anexos_cliente[<?=$contAnexos_ppes?>][ppes_vinculo_relacion]" id="anexo_ppes_vinculo_relacion_<?=$contAnexos_ppes?>">
		                                                                <option value="">Seleccione...</option>
		                                                                <?php foreach($vinculo_relacion as $row):?>
		                                                                    <div class="col-md-6">
		                                                                        <option type="radio" value="<?=$row['vinculo_relacion']?>" <?= $row['vinculo_relacion'] == $valuesAnexos_ppes["ppes_vinculo_relacion"] ? 'selected' : '' ?>><?=$row['vinculo_relacion']?></option>
		                                                                    </div>
		                                                                <?php endforeach;?>
		                                                            </select>
		                                                        </th>
		                                                        <th>
		                                                            <input type="text" class="form-control" name="anexos_cliente[<?=$contAnexos_ppes?>][ppes_nombre]" value="<?=$valuesAnexos_ppes["ppes_nombre"]?>" id="anexo_ppes_nombre_<?=$contAnexos_ppes?>" data-anexo-required="true">
		                                                        </th>
		                                                        <th>
		                                                            <select class="form-control" name="anexos_cliente[<?=$contAnexos_ppes?>][ppes_tipo_identificacion]" id="anexos_ppes_tipo_identificacion" data-anexo-required="true">
		                                                                <option value="">Seleccione un tipo de documento...</option>
		                                                                <?php foreach($natural as $row):?>
		                                                                    <div class="col-md-6">
		                                                                        <option type="radio" value="<?=$row['id']?>" <?= ($valuesAnexos_ppes['ppes_tipo_identificacion'] == $row['id']) ? 'selected' : '' ?>><?= trim($row['descripcion']) . " (" . $row['codigo'] . ")"?></option>
		                                                                    </div>
		                                                                <?php endforeach;?>
		                                                            </select>
		                                                        </th>
		                                                        <th>
		                                                            <input type="text" class="form-control" name="anexos_cliente[<?=$contAnexos_ppes?>][ppes_no_documento]" value="<?=$valuesAnexos_ppes["ppes_no_documento"]?>" id="anexo_ppes_no_documento_<?=$contAnexos_ppes?>" data-anexo-required="true">
		                                                        </th>
		                                                        <th>
		                                                            <select class="form-control" name="anexos_cliente[<?=$contAnexos_ppes?>][ppes_nacionalidad]" id="anexos_ppes_nacionalidad_<?=$contAnexos_ppes?>">
		                                                                <option value="">Seleccione una nacionalidad...</option>
		                                                                <?php foreach($paises as $row):?>
		                                                                    <option value="<?=$row['id']?>" <?= $valuesAnexos_ppes["ppes_nacionalidad"] == $row['id'] ? 'selected' : ''?> ><?=$row['nombre_pais']?></option>
		                                                                <?php endforeach;?>
		                                                            </select>
		                                                            
		                                                        </th>
		                                                        <th>
		                                                            <input type="text" class="form-control" name="anexos_cliente[<?=$contAnexos_ppes?>][ppes_entidad]" value="<?=$valuesAnexos_ppes["ppes_entidad"]?>" id="anexo_ppes_entidad_<?=$contAnexos_ppes?>">
		                                                        </th>
		                                                        <th>
		                                                            <input type="text" class="form-control" name="anexos_cliente[<?=$contAnexos_ppes?>][ppes_cargo]" value="<?=$valuesAnexos_ppes["ppes_cargo"]?>" id="anexo_ppes_cargo_<?=$contAnexos_ppes?>">
		                                                        </th>
		                                                        <th>
		                                                            <input type="date" class="form-control" name="anexos_cliente[<?=$contAnexos_ppes?>][ppes_desvinculacion]" value="<?=$valuesAnexos_ppes["ppes_desvinculacion"]?>"  id="anexo_ppes_desvinculacion_<?=$contAnexos_ppes?>">
		                                                        </th>
		                                                    </tr>
		                                                <?php endforeach; ?>
		                                            <?php endif; ?>
	                                                <?php if($contAnexos_ppes <= 7 || (7-$contAnexos_ppes) != 0): ?>
	                                                    <?php for($i = ($contAnexos_ppes+1); $i <= 7 ; $i++): ?>
	                                                            <tr>
	                                                                <th>
																		<select class="form-control add_anexos_ppes" name="anexos_cliente[<?=$i;?>][ppes_vinculo_relacion]" id="anexo_ppes_vinculo_relacion_<?=$i?>">
																			<option value="">Seleccione...</option>
																			<?php foreach($vinculo_relacion as $row):?>
																				<div class="col-md-6">
																					<option type="radio" value="<?=$row['vinculo_relacion']?>"><?=$row['vinculo_relacion']?></option>
																				</div>
																			<?php endforeach;?>
																		</select>
	                                                                </th>
	                                                                <th>
	                                                                    <input type="text" class="form-control" name="anexos_cliente[<?=$i;?>][ppes_nombre]" id="anexo_ppes_nombre_<?=$i?>" data-anexo-required="true">
	                                                                </th>
	                                                                <th>
	                                                                    <select class="form-control" name="anexos_cliente[<?=$i;?>][ppes_tipo_identificacion]" id="anexo_ppes_tipo_identificacion_<?=$i?>" data-anexo-required="true">
	                                                                        <option value="">Seleccione un tipo de documento...</option>
	                                                                        <?php foreach($natural as $row):?>
	                                                                            <div class="col-md-6">
	                                                                                <option type="radio" value="<?=$row['id']?>"><?= trim($row['descripcion']) . " (" . $row['codigo'] . ")"?></option>
	                                                                            </div>
	                                                                        <?php endforeach;?>
	                                                                    </select>
	                                                                </th>
	                                                                <th>
	                                                                    <input type="text" class="form-control" name="anexos_cliente[<?=$i;?>][ppes_no_documento]" id="anexo_ppes_no_documento_<?=$i?>" data-anexo-required="true">
	                                                                </th>
	                                                                <th>
	                                                                    <select class="form-control" name="anexos_cliente[<?=$i;?>][ppes_nacionalidad]" id="anexo_ppes_nacionalidad_<?=$i?>">
	                                                                        <option value="">Seleccione una nacionalidad...</option>
	                                                                        <?php foreach($paises as $row):?>
	                                                                            <option value="<?=$row['id']?>"><?=$row['nombre_pais']?></option>
	                                                                        <?php endforeach;?>
	                                                                    </select>
	                                                                    
	                                                                </th>
	                                                                <th>
	                                                                    <input type="text" class="form-control" name="anexos_cliente[<?=$i;?>][ppes_entidad]" id="anexo_ppes_entidad_<?=$i?>">
	                                                                </th>
	                                                                <th>
	                                                                    <input type="text" class="form-control" name="anexos_cliente[<?=$i;?>][ppes_cargo]" id="anexo_ppes_cargo_<?=$i?>">
	                                                                </th>
	                                                                <th>
	                                                                    <input type="date" class="form-control" name="anexos_cliente[<?=$i;?>][ppes_desvinculacion]" id="anexo_ppes_desvinculacion_<?=$i?>">
	                                                                </th>
	                                                            </tr>
	                                                    <?php endfor; ?>
	                                                <?php endif; ?>
	                                            </tbody>
	                                        </table>
	                                    </div>
	                                </div>
	                                <div class="modal-footer">
	                                    <button type="button" class="btn btn-danger">Cerrar</button>
	                                	<button type="button" class="btn btn-success" id="btn-validar-anexo-peps">Validacion Anexo PEPS</button>
	                                </div>
	                            </div>
	                        </div>
	                    </div>						
				    </div>
				  </div>
				</div>
			<?php endif; ?>
			
			<?php if(!in_array($InfoCliente["estado_formulario_id"],[6,5]) || (in_array($InfoCliente["estado_formulario_id"],[6,5]) && empty($cliente['declaracion_origen_fondos']) ) ):?>
				<!-- DECLARACION ORIGEN DE FONDOS -->
				<div class="panel section-form" >
				  <div class="panel-heading" role="tab" id="headingThree">
				    <h4 class="panel-title">
				    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#declaracion_origen_fondos" aria-expanded="true" aria-controls="collapseThree">
				      <strong>DECLARACION ORIGEN DE FONDOS</strong>
				    </a>
				  </h4>
				  </div>
				  <div id="declaracion_origen_fondos" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
				    <div class="panel-body">
				      	<div class="form-group col-md-12">
	                        <label>Declaración origen de fondos:</label>
	                        <input class="form-control" type="text" name="declaracion_origen_fondos" id="declaracion_origen_fondos" value="<?=$cliente['declaracion_origen_fondos']?>" >
	                    </div>
				    </div>
				  </div>
				</div>
			<?php endif; ?>
			
			<?php if(!in_array($InfoCliente["estado_formulario_id"],[5,6])):?>
				<!-- ACTIVIDADES EN OPERACIONES INTERNACIONALES -->
				<div class="panel section-form" >
				  <div class="panel-heading" role="tab" id="headingThree">
				    <h4 class="panel-title">
				    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#actividades_operaciones_internacionales" aria-expanded="true" aria-controls="collapseThree">
				      <strong>ACTIVIDADES EN OPERACIONES INTERNACIONALES</strong>
				    </a>
				  </h4>
				  </div>
				  <div id="actividades_operaciones_internacionales" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
				    <div class="panel-body">
				      	<div class="col-md-12 content-radio-buttons">
	                        <label class="required-field title" for="operaciones_moneda_extranjera">¿Realiza transacciones en moneda extranjera?:</label>
	                        <div class="form-group">
	                            <label class="radio-inline"><input type="radio" name="operaciones_moneda_extranjera" class="campo_obligatorio" data-required="true" value="SI" <?= ($cliente['operaciones_moneda_extranjera'] == "SI") ? 'checked' : '' ?> onclick="checkboxEnabledField(true,this,'div#operaciones_moneda_extranjera','hide')">Si</label>
	                            <label class="radio-inline"><input type="radio" name="operaciones_moneda_extranjera" value="NO" <?= ($cliente['operaciones_moneda_extranjera'] == "NO") ? 'checked' : '' ?> onclick="checkboxEnabledField(false,this,'div#operaciones_moneda_extranjera','hide')">No</label>
	                            <label class="radio-inline"><input type="radio" name="operaciones_moneda_extranjera" value="VACIO" <?=($cliente['operaciones_moneda_extranjera'] == "VACIO") ? 'checked' : '' ?>>N/A</label>
								<small class="help-error-block"></small>
	                        </div>
	                    </div> 
						<div class="col-md-12 content-radio-buttons" <?=($cliente["operaciones_moneda_extranjera"] != "SI") ? 'style="display: none;"' : "" ?> id="operaciones_moneda_extranjera">
			               <div class="form-group">
	                            <?php $oper_mona_extranjera = explode(',',$cliente["tipo_operaciones_moneda_extranjera"]); ?>
	                            <?php foreach($opMonExtra as $row):?>
	                                <div class="col-md-6">
	                                    <label class="radio-inline"><input type="checkbox" name="tipo_operaciones_moneda_extranjera[]" id="tipo_operaciones_moneda_extranjera" value="<?=$row['id']?>" onclick="<?=($row["id"] == 5) ? "checkboxEnabledField(true,this,'div#tipo_operaciones_moneda_extranjera','hide')" : "javascript:void(0)" ; ?>" <?=(in_array($row['id'],$oper_mona_extranjera)) ? 'checked' : '' ?>><?=$row['desc_operacion']?></label>
	                                </div>
	                            <?php endforeach;?>
	                        </div>
	                        <div class="col-md-12 form-group" id="tipo_operaciones_moneda_extranjera" <?=(!in_array(5,$oper_mona_extranjera)) ? "style='display: none;'" : "" ?>>
	                            <hr>
	                            <label>Otra, ¿Cuál?</label>
	                            <input type="text" class="form-control" name="desc_operacion_mon_extr" id="desc_operacion_mon_extr" value="<?=$cliente['desc_operacion_mon_extr']?>">
	                        </div>            
			            </div>

						<div class="col-md-12 content-radio-buttons">
	                        <label class="required-field title" for="productos_exterior">¿Posee productos financieros en el exterior?:</label>
	                        <div  class="form-group">                           
	                            <label class="radio-inline"><input type="radio" data-required="true" name="productos_exterior" value="SI" class="radios productos_exterior campo_obligatorio" <?= ($cliente['productos_exterior'] == "SI") ? 'checked' : '' ?> onclick="checkboxEnabledField(true,this,'label#add_productos','hide')">Si</label>
	                            <label class="radio-inline"><input type="radio" name="productos_exterior" value="NO" class="radios productos_exterior" <?= ($cliente['productos_exterior'] == "NO") ? 'checked' : '' ?> onclick="checkboxEnabledField(false,this,'label#add_productos','hide')">No</label>
	                            <label class="radio-inline"><input type="radio" name="productos_exterior" value="VACIO" class="radios productos_exterior" <?= ($cliente['productos_exterior'] == "VACIO") ? 'checked' : '' ?>>N/A</label>
	                            <label class="radio-inline" id="add_productos" <?=($cliente["productos_exterior"] != "SI") ? 'style="display: none;"' : ''?>><button type="button" class="btn btn-sm btn-success" onclick="checkboxEnabledField(true,$('input[name=productos_exterior][value=SI]'),'div#productos_exterior','modal')">AGREGAR <small class="glyphicon glyphicon-plus"></small></button></label>
								<small class="help-error-block"></small>
	                        </div>
	                    </div>

						<div class="col-md-12 content-radio-buttons">
	                        <label class="required-field title" for="cuentas_moneda_exterior">¿Poseee cuentas en moneda extranjera?:</label>
	                        <div class="form-group">                           
	                            <label class="radio-inline"><input type="radio" data-required="true" name="cuentas_moneda_exterior" value="SI" class="radios cuentas_moneda_exterior campo_obligatorio" <?= ($cliente['cuentas_moneda_exterior'] == "SI") ? 'checked' : '' ?>>Si</label>
	                            <label class="radio-inline"><input type="radio" name="cuentas_moneda_exterior" value="NO" class="radios cuentas_moneda_exterior" <?= ($cliente['cuentas_moneda_exterior'] == "NO") ? 'checked' : '' ?>>No</label>
	                            <label class="radio-inline"><input type="radio" name="cuentas_moneda_exterior" value="VACIO" class="radios cuentas_moneda_exterior" <?=($cliente['cuentas_moneda_exterior'] == "VACIO") ? 'checked' : '' ?>>N/A</label>
								<small class="help-error-block"></small>
	                        </div>
	                    </div>
						
						<!-- MODAL PRODUCTOS FINANCIEROS -->
	                    <div class="modal fade" id="productos_exterior" tabindex="-1" role="dialog" aria-labelledby="myModal_productos_ext" aria-hidden="true" >
	                        <div class="modal-dialog" style="width:90%;">
	                            <div class="modal-content">
	                                <div class="modal-header">
	                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
	                                  <h4 class="modal-title" style="font-size: 20px !important;">Especifique los productos financieros en el siguiente cuadro</h4>
	                                </div>
	                                <div class="modal-body">
	                                    <div class="table-responsive">
	                                        <table class="table table-hover table-bordered" style="width: 1200px !important; ">
	                                            <thead>
	                                                <tr>
	                                                    <th>TIPO DE PRODUCTO</th>
	                                                    <th>IDENTIFICACIÓN DEL PRODUCTO</th>
	                                                    <th>ENTIDAD</th>
	                                                    <th>MONTO</th>
	                                                    <th>CIUDAD</th>
	                                                    <th>PAIS</th>
	                                                    <th>MONEDA</th>
	                                                </tr>
	                                            </thead>
	                                            <tbody>
	                                                <?php $contProductFin = 0; ?>
	                                                <?php if(isset($productos_financieros)): ?>
		                                                <?php foreach($productos_financieros as $keyProductosFinancieros => $valueProductosFinancieros): $contProductFin++; ?>
		                                                    <tr>
		                                                        <th class="hidden">
		                                                            <input type="hidden" name="productos_financieros[<?=$contProductFin?>][producto_id]" value="<?=$valueProductosFinancieros['id']?>">
		                                                        </th>
		                                                        <th>
		                                                            <input type="text" class="form-control" name="productos_financieros[<?=$contProductFin?>][tipo_producto]" id="tipo_producto" value="<?=$valueProductosFinancieros['tipo_producto']?>">
		                                                        </th>
		                                                        <th>
		                                                            <input type="text" class="form-control" name="productos_financieros[<?=$contProductFin?>][identificacion_producto]" id="identificacion_producto" value="<?=$valueProductosFinancieros['identificacion_producto']?>">
		                                                        </th>
		                                                        <th>
		                                                            <input type="text" class="form-control" name="productos_financieros[<?=$contProductFin?>][entidad]" id="entidad" value="<?=$valueProductosFinancieros['entidad']?>">
		                                                        </th>
		                                                        <th>
		                                                            <input type="text" class="currency form-control" name="productos_financieros[<?=$contProductFin?>][monto]" id="monto" value="<?=$valueProductosFinancieros['monto']?>" onkeyup="OnlyNumbers(this)">
		                                                        </th>
		                                                        <th>
																	<select class="form-control" name="productos_financieros[<?=$contProductFin?>][ciudad]" id="ciudad<?=$contProductFin?>" onchange="validateOtro(this)">
																		<option value="">Seleccione una ciudad...</option>
																		<?php foreach($ciudades as $row):?>
																			<option type="radio" value="<?=$row['nombre_ciudad']?>" <?= ($row['nombre_ciudad'] == $valueProductosFinancieros['ciudad']) ? 'selected' : '' ?>><?=$row['nombre_ciudad']?></option>
																		<?php endforeach;?>
																		<option value="Otro">Otro</option>
																	</select>
																	<input type="text" class="form-control setValueOtro" name="txt_productos_financieros[<?=$contProductFin?>][ciudad]" id="txt_ciudad<?=$i?>" placeholder="¿Cuál?" <?=(isset($valueProductosFinancieros['ciudad']) && !(is_null($valueProductosFinancieros['ciudad']))) ? 'value="'.$valueProductosFinancieros['ciudad'].'" data-valorselect="true" style="display: block"' : 'style="display: none"' ?>>
		                                                        </th>
		                                                        <th>
																	<select class="form-control" name="productos_financieros[<?=$contProductFin?>][pais]" id="pais">
																		<option value="">Seleccione un pais...</option>
																		<?php foreach($paises as $row):?>
																			<option type="radio" value="<?=$row['id']?>" <?= ($row['nombre_pais'] == $valueProductosFinancieros['pais']) ? 'selected' : '' ?>><?=$row['nombre_pais']?></option>
																		<?php endforeach;?>
																	</select>
		                                                        </th>
		                                                        <th>
																	<select class="form-control" name="productos_financieros[<?=$contProductFin?>][moneda]" id="moneda">
																		<option value="">Seleccione una moneda...</option>
																		<?php foreach($monedas as $row):?>
																			<option type="radio" value="<?=$row['Descripcion']?>" <?= ($row['Descripcion'] == $valueProductosFinancieros['moneda']) ? 'selected' : '' ?>><?=$row['Descripcion'] . " (" . $row['Codigo'] . ")" ?></option>
																		<?php endforeach;?>
																	</select>
		                                                        </th>
		                                                    </tr>
		                                                <?php endforeach; ?>
		                                            <?php endif; ?>
	                                                <?php if($contProductFin <= 3 || (3-$contProductFin) != 0): ?>
	                                                    <?php for($i = ($contProductFin+1); $i <= 3; $i++): ?>
	                                                                <tr>
	                                                                    <th>
	                                                                        <input type="text" class="form-control" name="productos_financieros[<?=$i?>][tipo_producto]" id="tipo_producto">
	                                                                    </th>
	                                                                    <th>
	                                                                        <input type="text" class="form-control" name="productos_financieros[<?=$i?>][identificacion_producto]" id="identificacion_producto">
	                                                                    </th>
	                                                                    <th>
	                                                                        <input type="text" class="form-control" name="productos_financieros[<?=$i?>][entidad]" id="entidad">
	                                                                    </th>
	                                                                    <th>
	                                                                        <input type="text" class="currency form-control" name="productos_financieros[<?=$i?>][monto]" id="monto" onkeyup="OnlyNumbers(this)">
	                                                                    </th>
	                                                                    <th>
																			<select class="form-control" name="productos_financieros[<?=$i?>][ciudad]" id="ciudad<?=$i?>" onchange="validateOtro(this)">
																				<option value="">Seleccione una ciudad...</option>
																				<?php foreach($ciudades as $row):?>
																					<option type="radio" value="<?=$row['nombre_ciudad']?>"><?=$row['nombre_ciudad']?></option>
																				<?php endforeach;?>
																				<option value="Otro">Otro</option>
																			</select>
																			<input type="text" class="form-control" name="txt_productos_financieros[<?=$i?>][ciudad]" id="txt_ciudad<?=$i?>" placeholder="¿Cuál?" style="display: none">
	                                                                    </th>
	                                                                    <th>
																			<select class="form-control" name="productos_financieros[<?=$contProductFin?>][pais]" id="pais">
																				<option value="">Seleccione un pais...</option>
																				<?php foreach($paises as $row):?>
																					<option type="radio" value="<?=$row['id']?>"><?=$row['nombre_pais']?></option>
																				<?php endforeach;?>
																			</select>
	                                                                    </th>
	                                                                    <th>
																			<select class="form-control" name="productos_financieros[<?=$i?>][moneda]" id="moneda">
																				<option value="">Seleccione una moneda...</option>
																				<?php foreach($monedas as $row):?>
																					<option type="radio" value="<?=$row['Descripcion']?>" ><?=$row['Descripcion'] . " (" . $row['Codigo'] . ")" ?></option>
																				<?php endforeach;?>
																			</select>
	                                                                    </th>
	                                                                </tr>
	                                                    <?php endfor; ?>
	                                                <?php endif; ?>
	                                            </tbody>
	                                        </table>
	                                    </div>
	                                </div>
	                                <div class="modal-footer">
	                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
	                                </div>
	                            </div>
	                        </div>
	                    </div>
				    </div>
				  </div>
				</div>
			
				<!-- INFORMACION SOBRE RECLAMACIONES EN SEGUROS -->
				<div class="panel section-form" >
				  	<div class="panel-heading" role="tab" id="headingThree">
					    <h4 class="panel-title">
					    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#informacion_reclamaciones_seguros" aria-expanded="true" aria-controls="collapseThree">
					      <strong>INFORMACION SOBRE RECLAMACIONES EN SEGUROS</strong>
					    </a>
					  </h4>
				  	</div>
				  	<div id="informacion_reclamaciones_seguros" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
				    	<div class="panel-body">
					      	<div class="col-md-12 content-radio-buttons">
		                        <label class="required-field title" for="reclamaciones">¿Ha presentado reclamaciones o ha recibido indemnizacion en seguros en los dos ultimos años?:</label>
		                        <div class="form-group">
		                            <label class="radio-inline"><input type="radio" name="reclamaciones" data-required="true" value="1" class="radios reclamaciones" <?=($cliente['reclamaciones'] == '1') ? 'checked' : '' ?> onclick="checkboxEnabledField(true,this,'label#add_reclamaciones','hide')">Si</label>
		                            <label class="radio-inline"><input type="radio" name="reclamaciones" value="0" class="radios reclamaciones" <?=($cliente['reclamaciones'] === '0') ? 'checked' : '' ?> onclick="checkboxEnabledField(false,this,'label#add_reclamaciones','hide')">No</label>
		                            <label class="radio-inline"><input type="radio" name="reclamaciones" class="radios reclamaciones" <?=(is_null($cliente['reclamaciones'])) ? 'checked' : '' ?>>N/A</label>
	                            	<label class="radio-inline" id="add_reclamaciones" <?=($cliente["reclamaciones"] != '1') ? 'style="display: none;"' : ''?>><button type="button" class="btn btn-sm btn-success" onclick="checkboxEnabledField(true,$('input[name=reclamaciones][value=1]'),'div#reclamaciones','modal')">AGREGAR <small class="glyphicon glyphicon-plus"></small></button></label>
		                        </div>
		                    </div>
							
							<!-- MODAL RECLAMACIONES SEGUROS -->
							<div class="modal fade" id="reclamaciones" tabindex="-1" role="dialog" aria-labelledby="myModal_reclamaciones" aria-hidden="true" >
								<div class="modal-dialog" style="width:90%;">
									<div class="modal-content">
										<div class="modal-header">
								          <button type="button" class="close" data-dismiss="modal">&times;</button>
								          <h4 class="modal-title" style="font-size: 20px !important;">Especifique las reclamaciones en seguros en el siguiente cuadro</h4>
								        </div>
										<div class="modal-body">
											<div class="table-responsive">
												<table class="table table-hover table-bordered" style="width: 1200px !important; ">
													<thead>
								                		<tr>
								                			<th width="150">AÑO</th>
								                			<th>RAMO</th>
								                			<th>COMPAÑIA</th>
								                			<th width="200">VALOR</th>
								                			<th>RESULTADO</th>
								                		</tr>
								                	</thead>
													<tbody>
														<tr>
															<th>
																<select class="form-control" name="reclamacion_anio" id="reclamacion_anio">
																	<option value="">Seleccione año...</option>
																	<?php foreach($anio as $row):?>
																		<option type="radio" value="<?=$row['Anio']?>"><?=$row['Anio']?></option>
																	<?php endforeach;?>
																</select>
						                                    </th>
						                                    <th>
						                                        <input type="text" class="form-control" name="reclamacion_ramo" id="reclamacion_ramo" value="<?=$cliente['reclamacion_ramo']?>">
						                                    </th>
						                                    <th>
						                                        <input type="text" class="form-control" name="reclamacion_compania" id="reclamacion_compania" value="<?=$cliente['reclamacion_compania']?>">
						                                    </th>
						                                    <th>
						                                        <input type="text" class="currency form-control" name="reclamacion_valor" id="reclamacion_valor" value="<?=$cliente['reclamacion_valor']?>" onkeyup="OnlyNumbers(this)">
						                                    </th>
						                                    <th>
						                                    	<select name="reclamacion_resultado" id="reclamacion_resultado" class="form-control">
									                                <option value="">Seleccione resultado...</option>
									                                <option value="1" <?= $cliente['reclamacion_resultado'] == 1 ? 'selected' : ''?>>RECLAMACIÓN</option>
									                                <option value="2" <?= $cliente['reclamacion_resultado'] == 2 ? 'selected' : ''?>>INDEMNIZACIÓN</option>
									                            </select>
						                                    </th>
								                        </tr>
								                        <tr>
															<th>
																<select class="form-control" name="reclamacion_anio_2" id="reclamacion_anio_2">
																	<option value="">Seleccione año...</option>
																	<?php foreach($anio as $row):?>
																		<option type="radio" value="<?=$row['Anio']?>"><?=$row['Anio']?></option>
																	<?php endforeach;?>
																</select>
						                                    </th>
						                                    <th>
						                                        <input type="text" class="form-control" name="reclamacion_ramo_2" id="reclamacion_ramo_2" value="<?=$cliente['reclamacion_ramo_2']?>">
						                                    </th>
						                                    <th>
						                                        <input type="text" class="form-control" name="reclamacion_compania_2" id="reclamacion_compania_2" value="<?=$cliente['reclamacion_compania_2']?>">
						                                    </th>
						                                    <th>
						                                        <input type="text" class="currency form-control" name="reclamacion_valor_2" id="reclamacion_valor_2" value="<?=$cliente['reclamacion_valor_2']?>" onkeyup="OnlyNumbers(this)">
						                                    </th>
						                                    <th>
						                                    	<select name="reclamacion_resultado_2" id="reclamacion_resultado_2" class="form-control">
									                                <option value="">Seleccione resultado...</option>
									                                <option value="1" <?= $cliente['reclamacion_resultado_2'] == 1 ? 'selected' : ''?>>RECLAMACIÓN</option>
									                                <option value="2" <?= $cliente['reclamacion_resultado_2'] == 2 ? 'selected' : ''?>>INDEMNIZACIÓN</option>
									                            </select>
						                                    </th>
								                        </tr>
													</tbody>
												</table>
											</div>
										</div>
										<div class="modal-footer">
									        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
									    </div>
									</div>
								</div>
							</div>
				    	</div>
				  	</div>
				</div>
			
				<!-- CHECK LIST DOCUMENTOS EXISTENTES -->
				<div class="panel section-form" >
				  <div class="panel-heading" role="tab" id="headingThree">
				    <h4 class="panel-title">
				    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#checklist_documentos_existentes" aria-expanded="true" aria-controls="collapseThree">
				      <strong>CHECK LIST DOCUMENTOS EXISTENTES</strong>
				    </a>
				  </h4>
				  </div>
				  <div id="checklist_documentos_existentes" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
				    <div class="panel-body">
			            <div class="form-group <?=(is_null($InfoCliente['NOMBRE_CLIENTE']) || $InfoCliente['NOMBRE_CLIENTE'] == 'VACIO') ? 'hidden' : ''?>">
			            	<label>Nombre tomador:</label>
			            	<div class="input-group">
			            	    <input type="text" class="form-control" name="nombre_tomador" id="nombre_tomador" value="<?=$InfoCliente['NOMBRE_CLIENTE']?>" disabled='true'/>
			            	    <span class="input-group-addon"><span class="glyphicon glyphicon-pencil"></span></span>
			            	</div>
			            </div>
		                <div class="form-group">
		                    <label>Identificación tomador:</label>
		                    <input type="text" class="form-control" name="documento" id="documento" disabled="true" value="<?=$InfoCliente['documento']?>"/>
		                </div>

						<div class="form-group">
		                    <label>Fecha formulario:</label>
		                    <input type="text" class="form-control" name="fecha_diligenciamiento_check" disabled value="<?=$InfoCliente['fecha_diligenciamiento']?>"/>
		                </div>
		                <div class="col-md-12 content-radio-buttons">
	                        <label class="required-field title">Formulario Sarlaft:</label>
	                        <div class="form-group" id="ul-sarlaft">
	                            <label class="radio-inline">
	                                <input type="radio" name="sarlaft" class="radios sarlaft" value="1" disabled <?=(int)$chk_sarlaft_client == 1 ? "checked" : ""?>>Si
	                            </label>
	                            <label class="radio-inline">
	                                <input type="radio" name="sarlaft" class="radios sarlaft" value="0" disabled <?=(int)$chk_sarlaft_client == 0 ? "checked" : ""?>>No
	                            </label>
	                        </div>
		                </div>
			            <div class="col-md-12 content-radio-buttons">
	                        <label class="required-field title">Documentos:</label>
	                        <div class="form-group" id="ul-chk_documento">
	                            <label class="radio-inline">
	                                <input type="radio" name="chk_documento" class="radios chk_documento" value="1" disabled <?=(!isset($cliente["falta"])) ? "checked" : ""?>>Si
	                            </label>
	                            <label class="radio-inline">
	                                <input type="radio" name="chk_documento" class="radios chk_documento" value="0" disabled <?=(isset($cliente["falta"])) ? "checked" : ""?>>No
	                            </label>
	                        </div>
	                        <hr>
							<?php if(isset($cliente["documentos_faltantes"]) && !empty($cliente["documentos_faltantes"])): ?>
								<label class="required-field">Los siguiente documentos son requeridos para continuar el proceso por favor ingreselos:</label>
								<hr>
								<ul class="list-group">
									<?php foreach($cliente["documentos_faltantes"] AS $documento_faltante): ?>
										<li class="list-group-item text-danger" style="border: 1px solid #f00;"><?=("DOCUMENTO - ".$documento_faltante)?></li>
									<?php endforeach; ?>
								</ul>
							<?php endif; ?>
			            </div>
			            <div class="col-md-12 content-radio-buttons">
	                        <label class="required-field title">Otro:</label>
	                        <div class="form-group" id="ul-otros">
	                            <label class="radio-inline">
	                                <input type="radio" name="otro" class="radios otro" value="1" disabled <?=$cliente["otro"] == '1' ? "checked" : ""?>>Si
	                            </label>
	                            <label class="radio-inline">
	                                <input type="radio" name="otro" class="radios otro" value="0" disabled <?=$cliente["otro"] === '0' ? "checked" : ""?>>No
	                            </label>
	                        </div>
			            </div>
			            <div class="col-md-12 content-radio-buttons">
	                        <label class="required-field title" for="firma">¿Formulario con firma?:</label>
	                        <div class="form-group">
	                            <label class="radio-inline"><input type="radio" data-required="true" name="firma" class="radios firma" value="1" <?=$cliente["firma"] == '1' ? "checked" : ""?>>Si</label>
	                            <label class="radio-inline"><input type="radio" name="firma" class="radios firma" value="0" <?=$cliente["firma"] === '0' ? "checked" : "" ?>>No</label>
	                        </div>
			            </div>
			            <div class="col-md-12 content-radio-buttons">
	                        <label class="required-field title" for="huella">¿Formulario con huella?:</label>
	                        <div class="form-group">
	                            <label class="radio-inline"><input type="radio" data-required="true" name="huella" class="radios huella" value="1" <?=$cliente["huella"] == '1' ? "checked" : ""?>>Si</label>
	                            <label class="radio-inline"><input type="radio" name="huella" class="radios huella" value="0" <?=$cliente["huella"] === '0' ? "checked" : "" ?>>No</label>
	                        </div>
			            </div>
			            <div class="col-md-12 content-radio-buttons">
	                        <label class="required-field title">¿Formulario con entrevista?:</label>
	                        <div class="form-group" id="ul-entrevista">
	                            <label class="radio-inline"><input type="radio" name="entrevista" class="radios firma" value="1" <?=$cliente["entrevista"] == '1' ? "checked" : ""?> onclick='checkboxEnabledField(true,this,"div#informacion_entrevista","hide")'>Si</label>
	                            <label class="radio-inline"><input type="radio" name="entrevista" class="radios firma" value="0" <?=$cliente["entrevista"] === '0' ? "checked" : "" ?> onclick='checkboxEnabledField(false,this,"div#informacion_entrevista","hide")'>No</label>
	                        </div>
			            </div>
			            <div class="col-md-12 content-radio-buttons">
                            <label class="required-field title">¿Formulario con verificación?:</label>
                            <div class="form-group">
                                <label class="radio-inline"><input type="radio" name="verificacion" class="radios firma" value="1" <?=$cliente["verificacion"] == '1' ? "checked" : ""?> >Si</label>
                                <label class="radio-inline"><input type="radio" name="verificacion" class="radios firma" value="0" <?=$cliente["verificacion"] === '0' ? "checked" : ""?>>No</label>
                            </div>
                        </div>
                        <div class="col-md-12 content-radio-buttons">
                            <label class="required-field title" for="autoriza_tratamiento">Autorizacion tratamiento de informacion fines comerciales:</label>
                            <div class="form-group">
                                <label class="radio-inline"><input type="radio" name="autoriza_tratamiento" class="radios firma campo_obligatorio" value="SI" <?=$cliente["autoriza_tratamiento"] == "SI" ? "checked" : "" ?> data-required="true" >Si</label>
                                <label class="radio-inline"><input type="radio" name="autoriza_tratamiento" class="radios firma" value="NO" <?=$cliente["autoriza_tratamiento"] == "NO" ? "checked" : ""?>>No</label>
								<label class="radio-inline"><input type="radio" name="autoriza_tratamiento" class="radios firma" value="VACIO" <?=$cliente["autoriza_tratamiento"] == "VACIO" ? "checked" : ""?>>N/A</label>
								<small class="help-error-block"></small>
                            </div>
                        </div>
						<div class="col-md-12 content-radio-buttons">
                            <label class="title required-field" for="autoriza_info_fasecolda">Autorización tratamiento de información fasecolda:</label>
                            <div class="form-group">
                                <label class="radio-inline"><input type="radio" name="autoriza_info_fasecolda" class="radios firma campo_obligatorio" value="SI" <?=$cliente["autoriza_info_fasecolda"] == "SI" ? "checked" : ""?> data-required="true" >Si</label>
                                <label class="radio-inline"><input type="radio" name="autoriza_info_fasecolda" class="radios firma" value="NO" <?=$cliente["autoriza_info_fasecolda"] == "NO" ? "checked" : "" ?>>No</label>
								<label class="radio-inline"><input type="radio" name="autoriza_info_fasecolda" class="radios firma" value="VACIO" <?=$cliente["autoriza_info_fasecolda"] == "VACIO" ? "checked" : "" ?>>N/A</label>
								<small class="help-error-block"></small>
                            </div>
                        </div>
	                	<div  class="col-md-12" id="informacion_entrevista" <?=$cliente["entrevista"] != 1 ? "style='display:none;'" : ""?>> 
	                	    <div class="form-group">
	                	       <label class="control-label" for="entrevista_fecha">Fecha de la Entrevista:</label>
	                	       <input type="date" name="entrevista_fecha" id="entrevista_fecha" class="form-control" value="<?=$cliente['entrevista_fecha'] ?>" max=<?=(date("Y-m-d"))?>>
	                	    </div>
	                	    <div class="form-group" id="entrevista_observacion">
	                	       <label class="control-label" for="entrevista_observacion">Observaciones:</label>
	                	       <input type="text" class="form-control" name="entrevista_observaciones" id="entrevista_observaciones" class="form-control" value="<?=$cliente['entrevista_observaciones'] ?>" >
	                	    </div> 
	                	    <div class="col-md-12 content-radio-buttons">
	                	       <label class="title" for="entrevista_resultado">Resultado de la Entrevista:</label>
	                	       <div class="form-group">
	                	           <label class="radio-inline"><input type="radio" name="entrevista_resultado" value="APROBADO" <?=($cliente["entrevista_resultado"] == 'APROBADO') ? 'checked' : '' ?>>APROBADO</label>
	                	           <label class="radio-inline"><input type="radio" name="entrevista_resultado" value="RECHAZADO" <?=($cliente["entrevista_resultado"] == 'RECHAZADO') ? 'checked' : '' ?>>RECHAZADO</label>
	                	           <label class="radio-inline"><input type="radio" name="entrevista_resultado" value="" <?=(is_null($cliente["entrevista_resultado"])) ? 'checked' : '' ?>>N/A</label>
	                	       </div>
	                	    </div> 
	                	</div>
				    </div>
				  </div>
				</div>
			<?php endif; ?>
		</div>
		<hr>
		<button type="button" class="btn btn-success btn-guardar" <?=(!in_array($InfoCliente["estado_formulario_id"],[1,5,6,11])) ? 'disabled' : '' ?> id="btn-guardar-formulario">Guardar <?=strtolower($InfoCliente["ESTADO_FORM"])?> <span class="glyphicon glyphicon-inbox"></span></button>
	</form>
</div>
<!-- FIN Formulario nuevo version 2.0 -->

<!-- VENTANAS MODALES -->
<div id="modal-natural" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">
        	<!-- TITULO DE LA VENTANA MODAL -->
        </h4>
      </div>
      <div class="modal-body">
      	<!-- CONTENIDO DE LA VENTANA MODAL -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      	<button type="button" class="btn btn-success btn-guardar"></button>
      </div>
    </div>

  </div>
</div>