<!-- CONTENEDOR RECARGA NUEVO CLIENTE ESTADO CAPTURA -->
<style>
    .div_label {
        width: 25%;
        display: inline-block;
    }

    .div_input {
        width: 74.6%;
        display: inline-block;
    }
</style>
<div class="container-fluid">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">PROCESO DOCUMENTAL</div>
            <div class="panel-body">
                <form action="<?=BASE_URL?>estado_clientes_sarlaft/consulta_ult_estado" name="formulario_consulta_clientes_sarlaft" method="POST">
                    <div class="form-group">
                        <label for="documento_cliente">NUMERO DOCUMENTO CLIENTE A CONSULTAR:</label>
                        <input type="text" class="form-control" name="documento_cliente" data-require="true">
                        <small class="help-error-block"></small>
                    </div>
                    <div class="form-group" id="tipo_documento" style="display:none">
                        <div class="div_label">
                            <label for="documento_cliente">TIPO DOCUMENTO:</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" name="tipo_documento" disabled readonly>
                        </div>
                    </div>
                    <div class="form-group" id="client_name" style="display:none">
                        <div class="div_label">
                            <label for="documento_cliente">NOMBRE DE CLIENTE:</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" name="nombre_cliente" disabled readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="div_label">
                            <label for="">FCC FECHA DILIGENCIAMIENTO</label>
                        </div>
                        <div class="div_input">
                            <input type="date" class="form-control" readonly="readonly" id="ult_fecha_actualizacion">
                        </div>
                    </div>
                    <div class="form-group" id="div_ult_fecha_expedicion_rut" style="display:none">
                        <div class="div_label">
                            <label for="">RUT</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" readonly="readonly" id="ult_fecha_expedicion_rut">
                        </div>
                    </div>
                    <div class="form-group" id="div_ult_fecha_expedicion_cco" style="display:none">
                        <div class="div_label">
                            <label for="">CÁMARA DE COMERCIO</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" readonly="readonly" id="ult_fecha_expedicion_cco">
                        </div>
                    </div>
                    <div class="form-group" id="div_ult_fecha_expedicion_ddc" style="display:none">
                        <div class="div_label">
                            <label for="">DOC. DE CONSTITUCIÓN</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" readonly="readonly" id="ult_fecha_expedicion_ddc">
                        </div>
                    </div>
                    <div class="form-group" id="div_ult_fecha_expedicion_acc" style="display:none">
                        <div class="div_label">
                            <label for="">COMP. ACCIONARIA</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" readonly="readonly" id="ult_fecha_expedicion_acc">
                        </div>
                    </div>
                    <div class="form-group" id="div_ult_fecha_expedicion_efc" style="display:none">
                        <div class="div_label">
                            <label for="">ESTADOS FINANCIEROS COMPLETOS</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" readonly="readonly" id="ult_fecha_expedicion_efc">
                        </div>
                    </div>
                    <div class="form-group" id="div_ult_fecha_expedicion_efi" style="display:none">
                        <div class="div_label">
                            <label for="">ESTADOS FINANCIEROS PARCIALES</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" readonly="readonly" id="ult_fecha_expedicion_efi">
                        </div>
                    </div>
                    <div class="form-group" id="div_ult_fecha_expedicion_nef" style="display:none">
                        <div class="div_label">
                            <label for="">NOTAS ESTADOS FINANCIEROS</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" readonly="readonly" id="ult_fecha_expedicion_nef">
                        </div>
                    </div>
                    <div class="form-group" id="div_ult_fecha_expedicion_rta" style="display:none">
                        <div class="div_label">
                            <label for="">DECLARACIÓN DE RENTA</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" readonly="readonly" id="ult_fecha_expedicion_rta">
                        </div>
                    </div>
                    <div class="form-group" id="div_ult_fecha_expedicion_ret" style="display:none">
                        <div class="div_label">
                            <label for="">CERTIFICADO DE INGRESOS Y RETENCIONES</label>
                        </div>
                        <div class="div_input">
                            <input type="text" class="form-control" readonly="readonly" id="ult_fecha_expedicion_ret">
                        </div>
                    </div>
                    <button class="btn btn-success" id="btn-consultar">Consultar <span class="glyphicon glyphicon-search"></span></button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-8 col-md-offset-2" id="contenido-response">
        <table class="table table-striped table-bordered" id="table-respuesta" style="display: none">
            <thead>
                <tr>
                    <th class="text-center" style="color: #1f70a9">Señor usuario tenga en cuenta las siguientes recomendaciones</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th id="resppuesta-consulta" height="100" class="text-center"></th>
                </tr>
                <tr>
                    <th class="text-center" style="color: #1f70a9">No olvide que el diligenciamiento del formulario Sarlaft solo es requerido una vez por cliente.</th>
                </tr>
            </tbody>
        </table>
    </div>
</div> 