<div class="form-login">
    <div class="login-image">
		<img src="<?= BASE_URL;?>public/img/logo_confianza.jpg" alt="<?=APP_NAME?>" title="<?=APP_NAME?>">
    </div>
    <form action="#" method="post" autocomplete="off">
        <ul>
            <div class="form-messages" style="display:none">
                <div class="image-load"></div>
                <div class="error-message" style="display:none"></div>
            </div>
            <li>
                <label>Usuario:</label>
                <input type="text" name="username" id="username">
            </li>
            <li>
                <label>Contraseña:</label>
                <input type="password" name="password" id="password">
            </li>
            <li>
                <button class="login-button">Ingresar</button>
            </li>
        </ul>
    </form>
</div>
<!-- Contenido completo de página -->
<?php if(isset($_GET[inv_sid])&&$_GET[inv_sid]==1):?>
  <script>
    //Usuario inactivo
    $( document ).ready(function() { 
        $(".form-messages").fadeIn(250).find(".error-message").html("Sesion invalida, se ha iniciado sesion en otro equipo").fadeIn(230);
        $("#username").addClass("error-input").focus(); 
    });  
  </script>
<?php endif;?>